<div class="uat-modal" id="uatModal" hidden>
    <section role="dialog" aria-modal="true" aria-labelledby="uatTitle">
        <header><div><span>UAT &amp; FEEDBACK</span><h3 id="uatTitle">Laporkan masalah atau saran</h3><p>Konteks halaman dan browser akan disertakan otomatis.</p></div><button type="button" id="uatClose">×</button></header>
        <form method="POST" action="{{ route('uat-feedback.store',absolute:false) }}" enctype="multipart/form-data">@csrf
            <div class="uat-grid"><label>Kategori<select name="category" required><option value="bug">Bug / Error</option><option value="usability">Sulit Digunakan</option><option value="data">Masalah Data</option><option value="performance">Lambat / Performance</option><option value="suggestion">Saran Fitur</option></select></label><label>Tingkat Dampak<select name="severity" required><option value="medium">Sedang</option><option value="low">Rendah</option><option value="high">Tinggi</option><option value="critical">Kritis — pekerjaan terhenti</option></select></label></div>
            <label>Judul Singkat<input name="title" maxlength="255" required placeholder="Contoh: Tombol simpan tidak merespons"></label>
            <label>Jelaskan yang Terjadi<textarea name="description" rows="5" maxlength="5000" required placeholder="Tuliskan langkah yang dilakukan, hasil yang muncul, dan hasil yang seharusnya..."></textarea></label>
            <label>Screenshot (opsional)<input type="file" name="screenshot" accept="image/png,image/jpeg,image/webp"><small>Maksimal 5 MB, format PNG/JPG/WebP.</small></label>
            <input type="hidden" name="page_url" id="uatPageUrl"><input type="hidden" name="route_name" value="{{ Route::currentRouteName() }}"><input type="hidden" name="browser" id="uatBrowser">
            <footer><button type="button" id="uatCancel">Batal</button><button class="primary" type="submit">Kirim Laporan</button></footer>
        </form>
    </section>
</div>
<style>
    .uat-modal{position:fixed;z-index:16000;inset:0;display:grid;place-items:center;padding:16px;background:rgba(8,25,48,.58);backdrop-filter:blur(4px)}.uat-modal[hidden]{display:none}.uat-modal>section{width:min(620px,100%);max-height:90vh;overflow:auto;border-radius:15px;background:#fff;box-shadow:0 28px 70px rgba(4,24,50,.35)}.uat-modal header{display:flex;justify-content:space-between;padding:18px 20px;border-bottom:1px solid #e2e9f1}.uat-modal header span{color:#0870df;font-size:9px;font-weight:900;letter-spacing:.13em}.uat-modal h3,.uat-modal header p{margin:0}.uat-modal h3{margin-top:4px;font-size:16px}.uat-modal header p{margin-top:4px;color:#74869a;font-size:10px}.uat-modal header>button{border:0;background:transparent;color:#718397;font-size:25px;cursor:pointer}.uat-modal form{display:grid;gap:12px;padding:18px 20px}.uat-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.uat-modal label{display:grid;gap:5px;color:#405a74;font-size:10px;font-weight:800}.uat-modal input,.uat-modal select,.uat-modal textarea{box-sizing:border-box;width:100%;padding:9px 10px;border:1px solid #cbd8e5;border-radius:8px;outline:0;font:inherit;font-size:11px}.uat-modal textarea{resize:vertical}.uat-modal input:focus,.uat-modal select:focus,.uat-modal textarea:focus{border-color:#1b78dd;box-shadow:0 0 0 3px #e4f1ff}.uat-modal label small{color:#8595a6;font-size:8px}.uat-modal footer{display:flex;justify-content:flex-end;gap:8px;margin-top:3px}.uat-modal footer button{padding:9px 12px;border:0;border-radius:8px;background:#eef3f8;color:#5d7084;font-size:10px;font-weight:800;cursor:pointer}.uat-modal footer button.primary{background:#0870df;color:#fff}@media(max-width:550px){.uat-grid{grid-template-columns:1fr}}
</style>
<script>document.addEventListener('DOMContentLoaded',()=>{const modal=document.getElementById('uatModal');const open=()=>{modal.hidden=false;document.body.style.overflow='hidden';document.getElementById('uatPageUrl').value=location.href;document.getElementById('uatBrowser').value=navigator.userAgent};const close=()=>{modal.hidden=true;document.body.style.overflow=''};document.querySelectorAll('[data-uat-open]').forEach(b=>b.addEventListener('click',open));document.getElementById('uatClose')?.addEventListener('click',close);document.getElementById('uatCancel')?.addEventListener('click',close);modal?.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)close()})});</script>
