@extends('layouts.app')
@section('title','Buat A00') @section('page-title','Buat A00 — New Project Declaration')
@section('breadcrumb')<a href="{{ route('control-project.a00.index',absolute:false) }}">A00</a> / Buat @endsection
@section('content')
@if(request()->boolean('embedded'))
<style>html,body{width:100%!important;min-width:0!important;min-height:100vh!important;margin:0!important;overflow-x:hidden!important;background:#f5f7fb!important;zoom:1!important;transform:none!important}.sidebar,.sidebar-overlay,.header,.breadcrumb,.footer,.costing-assistant{display:none!important}.app-wrapper{display:block!important;width:100%!important;min-height:0!important}.main-wrapper{display:block!important;margin:0!important;width:100%!important;min-height:0!important}.main-content{box-sizing:border-box!important;width:100%!important;max-width:none!important;margin:0!important;padding:10px 14px 90px!important}.form-wrap{box-sizing:border-box!important;width:100%!important;max-width:none!important;margin:0!important}.a00-hero{margin-top:0;padding:.8rem 1rem}.a00-code{height:54px;font-size:1.7rem}.steps{margin-bottom:.65rem}.section{margin-bottom:.65rem}.section h3{padding:.6rem .8rem!important}.grid{padding:.75rem!important;gap:.7rem!important}.actions{position:fixed!important;left:14px!important;right:14px!important;bottom:8px!important;margin:0!important}</style>
@endif
<style>
.form-wrap{max-width:1080px!important}.a00-hero{display:grid;grid-template-columns:100px 1fr auto;align-items:center;gap:1.1rem;background:linear-gradient(135deg,#082d70,#1553a0);color:#fff;padding:1.15rem 1.35rem;border-radius:14px;margin-bottom:1rem;box-shadow:0 8px 24px rgba(8,45,112,.18)}.a00-code{display:flex;align-items:center;justify-content:center;height:70px;border:2px solid rgba(255,255,255,.55);border-radius:10px;font-size:2.1rem;font-weight:900}.a00-hero h2{margin:0 0 .25rem;font-size:1.12rem}.a00-hero p{margin:0;color:#cfe0ff;font-size:.78rem}.a00-number{text-align:right}.a00-number small{display:block;color:#cfe0ff;margin-bottom:.3rem}.a00-number strong{font-size:.8rem}.steps{display:grid;grid-template-columns:repeat(5,1fr);gap:.5rem;margin-bottom:1rem}.step{display:flex;align-items:center;gap:.5rem;background:#fff;border:1px solid #dbe3ef;border-radius:9px;padding:.55rem .65rem;color:#53657d;font-size:.7rem;font-weight:700}.step span{display:inline-flex;align-items:center;justify-content:center;width:21px;height:21px;border-radius:50%;background:#dbeafe;color:#1e40af}.section{box-shadow:0 2px 8px rgba(15,23,42,.035)}.section h3{padding:.8rem 1rem!important;letter-spacing:.035em;border-bottom:1px solid #dbe3ef}.grid{grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:1rem!important;padding:1.05rem!important}.field input,.field select,.field textarea{min-height:40px;font-size:.82rem;transition:.15s}.field input:focus,.field select:focus,.field textarea:focus{outline:0;border-color:#2563eb;box-shadow:0 0 0 3px rgba(37,99,235,.1)}.field input:disabled{background:#f1f5f9;color:#475569;font-weight:700}.check-card{height:40px;display:flex!important;align-items:center;gap:.55rem;border:1px solid #cbd5e1;border-radius:8px;padding:0 .75rem;font-weight:500!important;background:#f8fafc}.check-card input{width:auto!important;min-height:auto}.actions{bottom:.5rem!important;z-index:4;box-shadow:0 8px 25px rgba(15,23,42,.13)}.actions-note{margin-right:auto;color:#64748b;font-size:.72rem}.form-error{background:#fee2e2;color:#991b1b;padding:.75rem 1rem;border:1px solid #fecaca;border-radius:9px;margin-bottom:1rem}@media(max-width:850px){.grid{grid-template-columns:repeat(2,1fr)!important}.steps{grid-template-columns:repeat(2,1fr)}.a00-hero{grid-template-columns:75px 1fr}.a00-number{grid-column:1/-1;text-align:left}}@media(max-width:520px){.grid{grid-template-columns:1fr!important}.field.span2{grid-column:span 1!important}.steps{grid-template-columns:1fr}}
.item-toolbar{display:flex;align-items:center;justify-content:space-between;padding:.75rem 1rem;background:#f8fafc;border-top:1px solid #e2e8f0}.item-toolbar p{margin:0;color:#64748b;font-size:.72rem}.add-item{border:1px solid #0b3478;background:#fff;color:#0b3478;border-radius:7px;padding:.48rem .75rem;font-weight:700;cursor:pointer}.project-item{margin:0 1rem 1rem;border:1px solid #cbd5e1;border-radius:10px;overflow:hidden}.project-item-head{display:flex;align-items:center;justify-content:space-between;padding:.55rem .75rem;background:#edf3fb;color:#123b75;font-size:.75rem;font-weight:800}.remove-item{border:0;background:#fee2e2;color:#b91c1c;border-radius:6px;padding:.3rem .55rem;font-weight:700;cursor:pointer}.project-item .grid{padding:.8rem!important}.item-wide{grid-column:span 2}
.items-entry{padding:0 1rem 1rem}.items-table-head,.project-item-row{display:grid;grid-template-columns:36px 1fr 1.15fr 1.3fr .75fr .58fr .72fr .75fr 38px;gap:.55rem;align-items:center}.items-table-head{padding:.55rem .6rem;background:#0b3478;color:#fff;border-radius:8px 8px 0 0;font-size:.66rem;font-weight:700}.project-item{margin:0;border:0;border-left:1px solid #dbe3ef;border-right:1px solid #dbe3ef;border-bottom:1px solid #dbe3ef;border-radius:0;overflow:visible}.project-item:last-child{border-radius:0 0 8px 8px}.project-item-row{padding:.55rem .6rem;background:#fff}.project-item-row:hover{background:#f8fbff}.item-number{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:#dbeafe;color:#1e40af;font-size:.7rem;font-weight:800}.item-cell input,.item-cell select{width:100%;height:36px;min-height:36px;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:6px;padding:.45rem .55rem;font-size:.76rem}.item-cell input:focus,.item-cell select:focus{outline:0;border-color:#2563eb;box-shadow:0 0 0 2px rgba(37,99,235,.1)}.item-check{display:flex;align-items:center;justify-content:center;gap:.25rem;font-size:.7rem}.item-check input{width:auto;height:auto;min-height:0}.remove-item{width:30px;height:30px;border:0;background:#fee2e2;color:#b91c1c;border-radius:6px;font-size:17px;line-height:1;cursor:pointer}.items-add-row{display:flex;justify-content:flex-end;padding-top:.65rem}.items-help{color:#64748b;font-size:.7rem;margin-right:auto}@media(max-width:950px){.items-table-head{display:none}.project-item{margin-bottom:.75rem;border:1px solid #dbe3ef!important;border-radius:8px!important}.project-item-row{grid-template-columns:36px repeat(2,1fr);border-radius:8px}.item-cell{position:relative;padding-top:16px}.item-cell::before{content:attr(data-label);position:absolute;top:0;left:0;font-size:.62rem;font-weight:700;color:#64748b}.remove-item{justify-self:end}}@media(max-width:600px){.project-item-row{grid-template-columns:32px 1fr}.item-cell{grid-column:2}.remove-item{grid-column:2}}
.schedule-wrap{padding:.85rem 1rem 1rem}.schedule-input-table{width:100%;max-width:760px;border-collapse:collapse;font-size:.78rem}.schedule-input-table td{padding:.32rem .4rem}.schedule-no{width:28px;text-align:right;color:#64748b}.schedule-label{width:210px;font-weight:600;color:#334155}.schedule-colon{width:12px}.date-parts{display:grid;grid-template-columns:58px 92px 82px;width:232px}.date-parts select,.date-parts input{height:34px;min-height:34px;border:1px solid #94a3b8;border-right:0;border-radius:0;padding:.3rem .4rem;background:#fff;font-size:.76rem;text-align:center}.date-parts>*:first-of-type{border-radius:6px 0 0 6px}.date-parts>*:last-of-type{border-right:1px solid #94a3b8;border-radius:0 6px 6px 0}.date-format{color:#64748b;font-size:.7rem}.tba-option{display:inline-flex;align-items:center;gap:.35rem;margin-left:.6rem;font-size:.72rem;color:#475569}.tba-option input{width:auto;min-height:auto}@media(max-width:650px){.schedule-input-table,.schedule-input-table tbody,.schedule-input-table tr,.schedule-input-table td{display:block}.schedule-input-table tr{padding:.55rem 0;border-bottom:1px solid #e2e8f0}.schedule-no,.schedule-colon{display:none!important}.schedule-label{width:auto;margin-bottom:.35rem}.date-format{margin-top:.25rem}.date-parts{width:100%;grid-template-columns:1fr 1.5fr 1.2fr}}
.general-doc{padding:.8rem 1rem}.general-row{display:grid;grid-template-columns:28px 185px 12px minmax(220px,1fr);align-items:center;gap:.4rem;max-width:780px;margin-bottom:.45rem}.general-row .row-no{text-align:right;color:#64748b;font-size:.72rem}.general-row label{font-size:.75rem;font-weight:600;color:#334155}.general-row input,.general-row select{width:100%;height:36px;min-height:36px;border:0;border-bottom:1px solid #64748b;border-radius:0;padding:.35rem .45rem;background:#fff;font-size:.78rem}.general-row input:focus,.general-row select:focus{outline:0;border-bottom:2px solid #2563eb;box-shadow:none}.project-items-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem;padding:0 1rem 1rem}.project-items-grid .project-item{border:1px solid #cbd5e1!important;border-radius:9px!important;overflow:hidden}.doc-item-head{display:flex;align-items:center;justify-content:space-between;padding:.5rem .7rem;background:#edf3fb;color:#123b75;font-size:.72rem;font-weight:800}.doc-item-body{padding:.65rem .75rem}.doc-item-row{display:grid;grid-template-columns:105px 10px 1fr;align-items:center;margin-bottom:.42rem}.doc-item-row:last-child{margin-bottom:0}.doc-item-row>label{font-size:.7rem;color:#334155;font-weight:600}.doc-item-row input,.doc-item-row select{width:100%;height:32px;min-height:32px;border:0;border-bottom:1px solid #94a3b8;border-radius:0;padding:.25rem .35rem;font-size:.74rem;background:#fff}.doc-inline{display:grid;grid-template-columns:1fr 65px 90px;gap:.35rem}.life-inline{display:grid;grid-template-columns:80px auto;align-items:center;gap:.55rem}.life-inline .item-check{justify-content:flex-start}.doc-item-head .remove-item{width:auto;height:auto;padding:.25rem .5rem;font-size:.68rem}@media(max-width:850px){.project-items-grid{grid-template-columns:1fr}}@media(max-width:600px){.general-row{grid-template-columns:1fr}.general-row .row-no,.general-row .row-colon{display:none}.doc-item-row{grid-template-columns:1fr}.doc-item-row .row-colon{display:none}.doc-item-row>label{margin-bottom:.2rem}}
</style>
<style>.form-wrap{max-width:1150px;margin:auto}.section{background:#fff;border:1px solid #dbe3ef;border-radius:12px;margin-bottom:1rem;overflow:hidden}.section h3{margin:0;padding:.75rem 1rem;background:#edf3fb;color:#123b75;font-size:.83rem;text-transform:uppercase}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;padding:1rem}.field.span2{grid-column:span 2}.field label{display:block;font-size:.75rem;font-weight:700;color:#475569;margin-bottom:.35rem}.field input,.field select,.field textarea{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:8px;padding:.62rem .7rem;font:inherit}.field textarea{min-height:80px}.actions{position:sticky;bottom:0;background:#fff;border:1px solid #dbe3ef;border-radius:10px;padding:.8rem 1rem;display:flex;justify-content:flex-end;gap:.6rem}.btn{border:0;border-radius:8px;padding:.68rem 1rem;font-weight:700;background:#0b3478;color:#fff;text-decoration:none;cursor:pointer}.btn.alt{background:#fff;color:#0b3478;border:1px solid #0b3478}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}} </style>
@if(request()->boolean('embedded'))
<style>.main-content>.form-wrap,.form-wrap,.form-wrap>form{width:100%!important;max-width:100%!important;min-width:0!important;margin-left:0!important;margin-right:0!important}.form-wrap .a00-hero,.form-wrap .steps,.form-wrap .section{width:100%!important;max-width:none!important;box-sizing:border-box!important}</style>
@endif
<style>.document-meta-wrap{display:grid;grid-template-columns:minmax(420px,1fr) minmax(320px,.75fr);gap:1rem;padding:1rem}.meta-input-table{width:100%;border-collapse:collapse;background:#fff;font-size:.75rem}.meta-input-table th{width:125px;padding:.45rem .6rem;border:1px solid #94a3b8;background:#f8fafc;text-align:left;color:#334155;white-space:nowrap}.meta-input-table td{padding:0;border:1px solid #94a3b8}.meta-input-table input,.meta-input-table select{display:block;width:100%;height:36px;min-height:36px;border:0!important;border-radius:0!important;padding:.4rem .6rem!important;background:#fff;font-size:.76rem;box-shadow:none!important}.meta-input-table input:focus,.meta-input-table select:focus{outline:2px solid #2563eb!important;outline-offset:-2px}.meta-input-table input:disabled{background:#f1f5f9;font-weight:700;color:#334155}.from-to-input{display:grid;grid-template-columns:1fr 24px 1fr;align-items:center}.from-to-input span{text-align:center;color:#64748b}.source-note{padding:.65rem .8rem;border:1px dashed #cbd5e1;border-radius:8px;color:#64748b;font-size:.7rem;background:#f8fafc;align-self:start}@media(max-width:850px){.document-meta-wrap{grid-template-columns:1fr}}@media(max-width:520px){.document-meta-wrap{padding:.7rem}.meta-input-table th{width:95px}.from-to-input{grid-template-columns:1fr}.from-to-input span{display:none}}</style>
<style>.approval-admin-note{margin:.8rem 1rem 0;padding:.65rem .75rem;border-left:3px solid #2563eb;background:#eff6ff;color:#334155;font-size:.72rem}.signature-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.8rem;padding:1rem}.signature-card{border:1px solid #cbd5e1;border-radius:9px;overflow:hidden;background:#fff}.signature-title{padding:.48rem .65rem;background:#edf3fb;color:#123b75;font-size:.72rem;font-weight:800}.signature-body{padding:.65rem}.signature-body label{display:block;margin-bottom:.3rem;color:#475569;font-size:.68rem;font-weight:700}.signature-body input[type=text]{box-sizing:border-box;width:100%;height:34px;border:1px solid #cbd5e1;border-radius:6px;padding:.4rem .55rem;font-size:.75rem}.approved-placeholder{display:flex;align-items:center;justify-content:center;height:82px;margin-top:.55rem;border:1px dashed #94a3b8;border-radius:6px;background:#f8fafc;color:#16803c;font-size:1.05rem;font-weight:900;letter-spacing:.14em}.approved-placeholder span{padding:.45rem .8rem;border:2px solid #16803c;border-radius:4px;transform:rotate(-4deg)}.approval-footer-fields{display:grid;grid-template-columns:220px 1fr;gap:.8rem;padding:0 1rem 1rem}.approval-footer-fields textarea{min-height:62px}@media(max-width:800px){.signature-grid{grid-template-columns:1fr}.approval-footer-fields{grid-template-columns:1fr}}</style>
<div class="form-wrap">
<div class="a00-hero"><div class="a00-code">A00</div><div><h2>New Project Declaration</h2><p>Lengkapi informasi project, schedule internal, dan jadwal customer.</p></div><div class="a00-number"><small>Doc. No</small><strong>Diisi manual</strong></div></div>
<div class="steps"><div class="step"><span>1</span>Dokumen</div><div class="step"><span>2</span>Sumber Project</div><div class="step"><span>3</span>Informasi Umum</div><div class="step"><span>4</span>Schedule</div><div class="step"><span>5</span>Penerbitan</div></div>
@if($errors->any())<div class="form-error"><strong>Form belum dapat disimpan.</strong><br>{{ $errors->first() }}</div>@endif
@if($sourceProject)<div class="approval-admin-note" style="margin-bottom:.75rem"><strong>Membuat A00 untuk project yang sudah terdaftar.</strong> {{ $sourceProjects->count() }} project terpilih akan ditautkan sebagai item dalam satu A00 yang sama tanpa membuat project baru.</div>@endif
@php
    $sourceRevision=$sourceProject?->revisions?->first();
    $sourceCustomerId=$sourceProject ? $customers->firstWhere('name',$sourceProject->customer)?->id : null;
    $sourceCategoryId=$sourceProject ? $categories->first(fn($category)=>$category->code===$sourceProject->product?->code||$category->name===$sourceProject->product?->name)?->id : $defaultCategoryId;
@endphp
<form method="POST" action="{{ route('control-project.a00.store',absolute:false) }}" enctype="multipart/form-data">@csrf @if(request()->boolean('embedded'))<input type="hidden" name="embedded" value="1">@endif
<section class="section"><h3>Identitas Dokumen A00</h3><div class="document-meta-wrap"><table class="meta-input-table"><tbody><tr><th>Doc. No *</th><td><input name="document_number" value="{{ old('document_number') }}" placeholder="Contoh: 0100/MKT-PROJECT/A00/VII/2026" required></td></tr><tr><th>Date *</th><td><input id="a00DocumentDate" type="date" name="document_date" value="{{ old('document_date',date('Y-m-d')) }}" required></td></tr><tr><th>Revision *</th><td><input name="revision" value="{{ old('revision','00') }}" required></td></tr><tr><th>From - To *</th><td><div class="from-to-input"><input name="from_department" value="{{ old('from_department','MKT') }}" required><span>—</span><input name="to_department" value="{{ old('to_department','TEAM PROJECT') }}" required></div></td></tr></tbody></table><div class="source-note"><strong>A00 — New Project Declaration</strong><br>Nomor dokumen sementara diisi manual. Pastikan nomor sesuai dokumen resmi dan belum pernah digunakan.</div></div></section>
<section class="section"><h3>Sumber Project — RFI/RFQ</h3><div class="document-meta-wrap"><table class="meta-input-table"><tbody><tr><th>Request Type</th><td><select name="request_type"><option value="">Pilih RFI/RFQ</option>@foreach(['RFI','RFQ','OTHER'] as $v)<option @selected(old('request_type')===$v)>{{ $v }}</option>@endforeach</select></td></tr><tr><th>Request No.</th><td><input name="request_number" value="{{ old('request_number') }}" placeholder="Nomor RFI/RFQ"></td></tr><tr><th>Received Date</th><td><input type="date" name="request_received_date" value="{{ old('request_received_date') }}"></td></tr><tr><th>Attachment</th><td><input type="file" name="source_file" accept=".pdf,.xls,.xlsx,.doc,.docx"></td></tr></tbody></table><div class="source-note"><strong>Dokumen sumber project</strong><br>Lampirkan RFI, RFQ, atau dokumen permintaan customer sebagai referensi penerbitan A00.</div></div></section>
<section class="section"><h3>Data Operasional Project <span style="color:#64748b;font-size:.68rem;font-weight:600;text-transform:none">— tidak dicetak pada New Project Declaration</span></h3><div class="grid"><div class="field"><label>Plant *</label><select name="plant_id" required><option value="">Pilih plant</option>@foreach($plants as $plant)<option value="{{ $plant->id }}" @selected((string)old('plant_id')===(string)$plant->id)>{{ $plant->code }} — {{ $plant->name }}</option>@endforeach</select></div><div class="field"><label>Periode *</label><input type="month" name="period" value="{{ old('period',date('Y-m')) }}" required></div><div class="field"><label>PIC Engineering *</label><select name="pic_engineering" required><option value="">Pilih PIC Engineering</option>@foreach($picsEngineering as $pic)<option value="{{ $pic->name }}" @selected(old('pic_engineering')===$pic->name)>{{ $pic->name }}</option>@endforeach</select></div><div class="field"><label>PIC Marketing *</label><select name="pic_marketing" required><option value="">Pilih PIC Marketing</option>@foreach($picsMarketing as $pic)<option value="{{ $pic->name }}" @selected(old('pic_marketing')===$pic->name)>{{ $pic->name }}</option>@endforeach</select></div></div></section>
<section class="section"><h3>I. General Information</h3><div class="general-doc"><div class="general-row"><span class="row-no">1.</span><label>Kategori Bisnis *</label><span class="row-colon">:</span><select name="business_category_id" required><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('business_category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="general-row"><span class="row-no">2.</span><label>Customer *</label><span class="row-colon">:</span><select name="customer_id" required><option value="">Pilih customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id')==$customer->id)>{{ $customer->name }}</option>@endforeach</select></div></div>
<div class="item-toolbar"><p>Isi informasi model dan assembly seperti pada dokumen A00.</p><button class="add-item" type="button" onclick="addProjectItem()">+ Tambah Item</button></div><div id="projectItems" class="project-items-grid"></div></section>
@php
 $monthLabels=[1=>'Jan',2=>'Feb',3=>'Mar',4=>'Apr',5=>'Mei',6=>'Jun',7=>'Jul',8=>'Agu',9=>'Sep',10=>'Okt',11=>'Nov',12=>'Des'];
 $internalSchedules=['due_part_list'=>'Due Date Part List','due_umh'=>'Due Date UMH','due_new_part_price'=>'Due Date Harga New Part','due_costing'=>'Due Date Costing','due_submit_quotation'=>'Submit Quotation'];
 $customerSchedules=['pp1_date'=>'PP1','pp2_date'=>'PP2','pp3_date'=>'PP3','sop_mp_date'=>'SOP/MP'];
@endphp
@php $documentDateDefault=old('document_date',date('Y-m-d')); @endphp
<section class="section"><h3>II. Schedule of Internal Project</h3><div class="schedule-wrap"><table class="schedule-input-table"><tbody>@foreach($internalSchedules as $name=>$label)@php $usesDocumentDefault=in_array($name,['due_part_list','due_umh'],true);$dateValue=old($name,$usesDocumentDefault?$documentDateDefault:null);$dateObj=$dateValue?\Carbon\Carbon::parse($dateValue):null;$manuallyChanged=$usesDocumentDefault&&$dateValue!==$documentDateDefault; @endphp<tr data-date-group @if($usesDocumentDefault) data-document-date-default data-default-manual="{{ $manuallyChanged?'1':'0' }}" @endif><td class="schedule-no">{{ $loop->iteration }}.</td><td class="schedule-label">{{ $label }}</td><td class="schedule-colon">:</td><td><input type="hidden" name="{{ $name }}" value="{{ $dateValue }}" data-date-value><div class="date-parts"><select data-day aria-label="Hari {{ $label }}"><option value="">DD</option>@for($day=1;$day<=31;$day++)<option value="{{ $day }}" @selected($dateObj?->day===$day)>{{ str_pad($day,2,'0',STR_PAD_LEFT) }}</option>@endfor</select><select data-month aria-label="Bulan {{ $label }}"><option value="">MMM</option>@foreach($monthLabels as $month=>$monthLabel)<option value="{{ $month }}" @selected($dateObj?->month===$month)>{{ $monthLabel }}</option>@endforeach</select><input data-year type="number" min="2000" max="2100" value="{{ $dateObj?->year }}" placeholder="YYYY" aria-label="Tahun {{ $label }}"></div></td><td class="date-format">(dd/mmm/yyyy)</td></tr>@endforeach</tbody></table></div></section>
<section class="section"><h3>III. Schedule of Customer Events</h3><div class="schedule-wrap"><table class="schedule-input-table"><tbody>@foreach($customerSchedules as $name=>$label)@php $dateValue=old($name);$dateObj=$dateValue?\Carbon\Carbon::parse($dateValue):null; @endphp<tr data-date-group @if($name==='sop_mp_date') data-tba-group @endif><td class="schedule-no">{{ $loop->iteration }}.</td><td class="schedule-label">{{ $label }}</td><td class="schedule-colon">:</td><td><input type="hidden" name="{{ $name }}" value="{{ $dateValue }}" data-date-value><div class="date-parts"><select data-day aria-label="Hari {{ $label }}"><option value="">DD</option>@for($day=1;$day<=31;$day++)<option value="{{ $day }}" @selected($dateObj?->day===$day)>{{ str_pad($day,2,'0',STR_PAD_LEFT) }}</option>@endfor</select><select data-month aria-label="Bulan {{ $label }}"><option value="">MMM</option>@foreach($monthLabels as $month=>$monthLabel)<option value="{{ $month }}" @selected($dateObj?->month===$month)>{{ $monthLabel }}</option>@endforeach</select><input data-year type="number" min="2000" max="2100" value="{{ $dateObj?->year }}" placeholder="YYYY" aria-label="Tahun {{ $label }}"></div></td><td class="date-format">(dd/mmm/yyyy) @if($name==='sop_mp_date')<label class="tba-option"><input type="checkbox" name="sop_mp_tba" value="1" data-tba @checked(old('sop_mp_tba'))> TBA</label>@endif</td></tr>@endforeach</tbody></table></div></section>
<section class="section"><h3>Penerbitan & Approval</h3><div class="approval-admin-note"><strong>Dikelola oleh Admin Control Project.</strong> Untuk sementara tanda tangan menggunakan penanda APPROVED. File tanda tangan PNG dapat diterapkan setelah tersedia.</div><div class="signature-grid">@foreach([['prepared','Dibuat oleh',auth()->user()->name],['acknowledged','Diketahui oleh',''],['approved','Disetujui oleh','']] as [$key,$label,$default])<div class="signature-card"><div class="signature-title">{{ $label }}</div><div class="signature-body"><label>Nama penandatangan</label><input type="text" name="{{ $key }}_by" value="{{ old($key.'_by',$default) }}" placeholder="Masukkan nama"><div class="approved-placeholder"><span>APPROVED</span></div></div></div>@endforeach</div><div class="approval-footer-fields"><div class="field"><label>Lokasi *</label><input name="issue_location" value="{{ old('issue_location','Cikarang') }}" required></div><div class="field"><label>Catatan</label><textarea name="notes">{{ old('notes') }}</textarea></div></div></section>
<div class="actions"><span class="actions-note">Field bertanda * wajib diisi.</span>@if(request()->boolean('embedded'))<button type="button" class="btn alt" onclick="parent.postMessage({type:'a00-cancel'},location.origin)">Batal</button>@else<a class="btn alt" href="{{ route('control-project.a00.index',absolute:false) }}">Batal</a>@endif<button class="btn">Terbitkan A00 & Buat Project</button></div>
</form></div>
@php
    $sourceItemDefaults = $sourceProjects->map(fn($project) => [
        'document_project_id' => $project->id,
        'model' => $project->model ?? '', 'assy_number' => $project->part_number ?? '',
        'assy_name' => $project->part_name ?? '', 'quantity' => '',
        'quantity_uom' => 'Pcs', 'quantity_basis' => 'per Year',
        'product_life_years' => '', 'spot_order' => false,
    ])->values()->all();
    $oldA00Items = old('items', $sourceItemDefaults ?: [[
        'document_project_id' => null, 'model' => '', 'assy_number' => '', 'assy_name' => '',
        'quantity' => '', 'quantity_uom' => 'Pcs', 'quantity_basis' => 'per Year',
        'product_life_years' => '', 'spot_order' => false,
    ]]);
    $sourceDefaults = [
        'business_category_id'=>$sourceCategoryId,
        'customer_id'=>$sourceCustomerId,
        'plant_id'=>$sourceRevision?->plant_id,
        'period'=>$sourceRevision?->period,
        'pic_engineering'=>$sourceRevision?->pic_engineering,
        'pic_marketing'=>$sourceRevision?->pic_marketing,
    ];
@endphp
<template id="projectItemTemplate"><div class="project-item"><div class="doc-item-head"><span>ITEM <b data-item-number></b></span><button class="remove-item" type="button" onclick="removeProjectItem(this)">Hapus</button></div><div class="doc-item-body"><div class="doc-item-row"><label>Model *</label><span class="row-colon">:</span><input data-name="model" placeholder="Contoh: K4MA" required></div><div class="doc-item-row"><label>Assy Name *</label><span class="row-colon">:</span><input data-name="assy_name" placeholder="Contoh: Cord Assy" required></div><div class="doc-item-row"><label>Assy No. *</label><span class="row-colon">:</span><input data-name="assy_number" placeholder="Contoh: W40294" required></div><div class="doc-item-row"><label>Quantity</label><span class="row-colon">:</span><div class="doc-inline"><input type="number" min="0" data-name="quantity" placeholder="0"><select data-name="quantity_uom" required><option>Pcs</option><option>Set</option><option>Unit</option></select><select data-name="quantity_basis" required><option>per Year</option><option>per Month</option><option>Spot Order</option></select></div></div><div class="doc-item-row"><label>Product's Life</label><span class="row-colon">:</span><div class="life-inline"><div style="display:flex;align-items:center"><input type="number" min="0" max="99" data-name="product_life_years" placeholder="0"><span style="font-size:.7rem;margin-left:.3rem">Years</span></div><label class="item-check"><input type="checkbox" value="1" data-name="spot_order"> Spot Order</label></div></div></div></div></template>
<script>
const projectItems=document.getElementById('projectItems'),itemTemplate=document.getElementById('projectItemTemplate');
const oldItems=@json($oldA00Items);
const sourceDefaults=@json($sourceDefaults);
Object.entries(sourceDefaults).forEach(([name,value])=>{const field=document.querySelector(`[name="${name}"]`);if(field&&value&&!field.value)field.value=value});
function refreshProjectItems(){[...projectItems.children].forEach((item,index)=>{item.querySelector('[data-item-number]').textContent=index+1;item.querySelectorAll('[data-name]').forEach(input=>input.name=`items[${index}][${input.dataset.name}]`);item.querySelector('.remove-item').style.visibility=projectItems.children.length===1?'hidden':'visible'})}
function addProjectItem(values={}){const item=itemTemplate.content.firstElementChild.cloneNode(true);const projectId=document.createElement('input');projectId.type='hidden';projectId.dataset.name='document_project_id';projectId.value=values.document_project_id||'';item.prepend(projectId);item.querySelectorAll('[data-name]').forEach(input=>{const value=values[input.dataset.name];if(input.type==='checkbox')input.checked=value===true||value===1||value==='1';else if(value!==undefined)input.value=value});projectItems.appendChild(item);refreshProjectItems();item.scrollIntoView({behavior:'smooth',block:'nearest'})}
function removeProjectItem(button){if(projectItems.children.length<=1)return;button.closest('.project-item').remove();refreshProjectItems()}
oldItems.forEach(item=>addProjectItem(item));
function syncDateGroup(group){const hidden=group.querySelector('[data-date-value]'),day=group.querySelector('[data-day]').value,month=group.querySelector('[data-month]').value,year=group.querySelector('[data-year]').value;if(day&&month&&year){const maxDay=new Date(Number(year),Number(month),0).getDate();if(Number(day)>maxDay){group.querySelector('[data-day]').value=maxDay}hidden.value=`${year}-${String(month).padStart(2,'0')}-${String(group.querySelector('[data-day]').value).padStart(2,'0')}`}else hidden.value=''}
document.querySelectorAll('[data-date-group]').forEach(group=>{group.querySelectorAll('[data-day],[data-month],[data-year]').forEach(input=>input.addEventListener('change',()=>{if(group.hasAttribute('data-document-date-default'))group.dataset.defaultManual='1';syncDateGroup(group)}));const tba=group.querySelector('[data-tba]');if(tba){const toggle=()=>{group.querySelectorAll('[data-day],[data-month],[data-year]').forEach(input=>input.disabled=tba.checked);if(tba.checked)group.querySelector('[data-date-value]').value='';else syncDateGroup(group)};tba.addEventListener('change',toggle);toggle()}});
document.getElementById('a00DocumentDate')?.addEventListener('change',event=>{const value=event.target.value;if(!value)return;const [year,month,day]=value.split('-');document.querySelectorAll('[data-document-date-default]').forEach(group=>{if(group.dataset.defaultManual==='1')return;group.querySelector('[data-day]').value=Number(day);group.querySelector('[data-month]').value=Number(month);group.querySelector('[data-year]').value=year;syncDateGroup(group)})});
</script>
@endsection
