@extends('layouts.app')
@section('title','Edit A00')
@section('page-title','Edit A00 — New Project Declaration')
@section('breadcrumb')<span>A00 / Edit New Project Declaration</span>@endsection
@section('content')
@if(request()->boolean('embedded'))<style>html,body{width:100%!important;min-width:0!important;margin:0!important;background:#f5f7fb!important;zoom:1!important;transform:none!important}.sidebar,.sidebar-overlay,.header,.breadcrumb,.footer,.costing-assistant{display:none!important}.app-wrapper,.main-wrapper{display:block!important;box-sizing:border-box!important;margin:0!important;width:100%!important;max-width:none!important;min-width:0!important}.main-content{box-sizing:border-box!important;width:100%!important;max-width:none!important;margin:0!important;padding:12px 14px 96px!important}.edit-wrap{width:100%!important;max-width:none!important;margin:0!important}</style>@endif
<style>.edit-wrap{max-width:1080px;margin:0 auto}.edit-section{margin-bottom:.8rem;border:1px solid #dbe5f2;border-radius:10px;background:#fff;overflow:hidden}.edit-section h3{margin:0;padding:.7rem .9rem;border-bottom:1px solid #dbe5f2;background:#edf3fb;color:#123b75;font-size:.75rem;text-transform:uppercase}.edit-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem;padding:.9rem}.edit-field label{display:block;margin-bottom:.3rem;color:#475569;font-size:.66rem;font-weight:800}.edit-field input,.edit-field select,.edit-field textarea{box-sizing:border-box;width:100%;min-height:36px;border:1px solid #cbd5e1;border-radius:6px;padding:.4rem .55rem;background:#fff;font-size:.73rem}.edit-field textarea{min-height:65px}.span2{grid-column:span 2}.span4{grid-column:1/-1}.item-card{margin:.75rem .9rem;border:1px solid #cbd5e1;border-radius:8px;overflow:hidden}.item-head{padding:.45rem .65rem;background:#f8fafc;color:#334155;font-size:.7rem;font-weight:850}.op-note{padding:.6rem .9rem;background:#eff6ff;color:#475569;font-size:.68rem}.edit-error{margin-bottom:.8rem;padding:.7rem .9rem;border:1px solid #fca5a5;border-radius:8px;background:#fef2f2;color:#991b1b}.edit-actions{position:fixed;right:30px;bottom:14px;z-index:5;display:flex;gap:.5rem;padding:.65rem;border:1px solid #dbe5f2;border-radius:9px;background:#fff;box-shadow:0 10px 30px rgba(15,23,42,.14)}.edit-btn{height:36px;padding:0 .85rem;border:1px solid #cbd5e1;border-radius:7px;background:#fff;color:#334155;font-weight:800;cursor:pointer}.edit-btn.primary{border-color:#0b3478;background:#0b3478;color:#fff}@media(max-width:800px){.edit-grid{grid-template-columns:repeat(2,1fr)}.span4{grid-column:span 2}}@media(max-width:520px){.edit-grid{grid-template-columns:1fr}.span2,.span4{grid-column:span 1}}</style>
<style>.edit-customer-events{padding:.9rem}.edit-customer-event-row{display:grid;grid-template-columns:32px minmax(180px,1fr) 180px 65px 34px;align-items:end;gap:.65rem;padding:.5rem 0;border-bottom:1px solid #e2e8f0}.edit-event-number{align-self:center;color:#64748b;font-size:.72rem;text-align:center}.edit-event-tba{display:flex;align-items:center;gap:.35rem;height:36px;color:#475569;font-size:.72rem}.edit-event-remove,.edit-event-add{border:1px solid #cbd5e1;border-radius:6px;background:#fff;font-weight:800;cursor:pointer}.edit-event-remove{width:30px;height:30px;margin-bottom:3px;border-color:#fecaca;background:#fef2f2;color:#b91c1c;font-size:18px}.edit-event-add{margin-top:.7rem;padding:.48rem .75rem;color:#0b3478}@media(max-width:700px){.edit-customer-event-row{grid-template-columns:28px 1fr 34px}.edit-customer-event-row .edit-field{grid-column:2}.edit-event-tba{grid-column:2}.edit-event-remove{grid-column:3;grid-row:1}}</style>
@php($revision=$a00->projectRevision)
<div class="edit-wrap">@if($errors->any())<div class="edit-error"><strong>Perubahan belum tersimpan.</strong><br>{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('control-project.a00.update',$a00,absolute:false) }}" enctype="multipart/form-data">@csrf @method('PUT') @if(request()->boolean('embedded'))<input type="hidden" name="embedded" value="1">@endif
<section class="edit-section"><h3>Identitas Dokumen A00</h3><div class="edit-grid"><div class="edit-field span2"><label>Nomor A00 *</label><input name="document_number" value="{{ old('document_number',$a00->document_number) }}" required></div><div class="edit-field"><label>Tanggal *</label><input type="date" name="document_date" value="{{ old('document_date',$a00->document_date?->format('Y-m-d')) }}" required></div><div class="edit-field"><label>Revision *</label><input name="revision" value="{{ old('revision',$a00->revision) }}" required></div><div class="edit-field"><label>From *</label><input name="from_department" value="{{ old('from_department',$a00->from_department) }}" required></div><div class="edit-field"><label>To *</label><input name="to_department" value="{{ old('to_department',$a00->to_department) }}" required></div></div></section>
<section class="edit-section"><h3>Sumber Project — RFI/RFQ</h3><div class="edit-grid"><div class="edit-field"><label>Request Type</label><select name="request_type"><option value="">Pilih</option>@foreach(['RFI','RFQ','OTHER'] as $type)<option @selected(old('request_type',$a00->request_type)===$type)>{{ $type }}</option>@endforeach</select></div><div class="edit-field"><label>Request No.</label><input name="request_number" value="{{ old('request_number',$a00->request_number) }}"></div><div class="edit-field"><label>Received Date</label><input type="date" name="request_received_date" value="{{ old('request_received_date',$a00->request_received_date?->format('Y-m-d')) }}"></div><div class="edit-field"><label>Ganti Attachment</label><input type="file" name="source_file" accept=".pdf,.xls,.xlsx,.doc,.docx"></div></div></section>
<section class="edit-section"><h3>Data Operasional Project — tidak dicetak</h3><div class="op-note">Data berikut dipakai oleh workflow dan Form Costing, tetapi tidak ditampilkan pada New Project Declaration.</div><div class="edit-grid"><div class="edit-field"><label>Plant *</label><select name="plant_id" required><option value="">Pilih plant</option>@foreach($plants as $plant)<option value="{{ $plant->id }}" @selected((string)old('plant_id',$revision?->plant_id)===(string)$plant->id)>{{ $plant->code }} — {{ $plant->name }}</option>@endforeach</select></div><div class="edit-field"><label>Periode *</label><input type="month" name="period" value="{{ old('period',$revision?->period) }}" required></div><div class="edit-field"><label>PIC Engineering *</label><select name="pic_engineering" required><option value="">Pilih PIC</option>@foreach($picsEngineering as $pic)<option value="{{ $pic->name }}" @selected(old('pic_engineering',$revision?->pic_engineering)===$pic->name)>{{ $pic->name }}</option>@endforeach</select></div><div class="edit-field"><label>PIC Marketing *</label><select name="pic_marketing" required><option value="">Pilih PIC</option>@foreach($picsMarketing as $pic)<option value="{{ $pic->name }}" @selected(old('pic_marketing',$revision?->pic_marketing)===$pic->name)>{{ $pic->name }}</option>@endforeach</select></div></div></section>
<section class="edit-section"><h3>I. General Information</h3><div class="edit-grid"><div class="edit-field"><label>Kategori Bisnis *</label><select name="business_category_id" required><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('business_category_id',$categories->firstWhere('code',$a00->project?->product?->code)?->id)===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="edit-field"><label>Customer *</label><select name="customer_id" required><option value="">Pilih customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)old('customer_id',$customers->firstWhere('name',$a00->customer)?->id)===(string)$customer->id)>{{ $customer->name }}</option>@endforeach</select></div></div>
@foreach($a00->items as $index=>$item)<div class="item-card"><div class="item-head">Assembly {{ $index+1 }}</div><input type="hidden" name="items[{{ $index }}][id]" value="{{ $item->id }}"><div class="edit-grid"><div class="edit-field"><label>Model *</label><input name="items[{{ $index }}][model]" value="{{ old("items.$index.model",$item->model) }}" required></div><div class="edit-field"><label>Assy Name *</label><input name="items[{{ $index }}][assy_name]" value="{{ old("items.$index.assy_name",$item->assy_name) }}" required></div><div class="edit-field"><label>Assy No. *</label><input name="items[{{ $index }}][assy_number]" value="{{ old("items.$index.assy_number",$item->assy_number) }}" required></div><div class="edit-field"><label>Quantity</label><input type="number" min="0" name="items[{{ $index }}][quantity]" value="{{ old("items.$index.quantity",$item->quantity) }}"></div><div class="edit-field"><label>UOM *</label><select name="items[{{ $index }}][quantity_uom]" required>@foreach(['Pcs','Set','Unit'] as $value)<option @selected(old("items.$index.quantity_uom",$item->quantity_uom)===$value)>{{ $value }}</option>@endforeach</select></div><div class="edit-field"><label>Basis *</label><select name="items[{{ $index }}][quantity_basis]" required>@foreach(['per Year','per Month','Spot Order'] as $value)<option @selected(old("items.$index.quantity_basis",$item->quantity_basis)===$value)>{{ $value }}</option>@endforeach</select></div><div class="edit-field"><label>Product Life (Years)</label><input type="number" min="0" max="99" name="items[{{ $index }}][product_life_years]" value="{{ old("items.$index.product_life_years",$item->product_life_years) }}"></div><div class="edit-field"><label>Spot Order</label><select name="items[{{ $index }}][spot_order]"><option value="0">Tidak</option><option value="1" @selected(old("items.$index.spot_order",$item->spot_order))>Ya</option></select></div></div></div>@endforeach</section>
<section class="edit-section"><h3>II. Schedule of Internal Project</h3><div class="edit-grid">@foreach(['due_part_list'=>'Due Date Part List','due_umh'=>'Due Date UMH','due_new_part_price'=>'Due Date Harga New Part','due_costing'=>'Due Date Costing','due_submit_quotation'=>'Submit Quotation'] as $field=>$label)<div class="edit-field"><label>{{ $label }}</label><input type="date" name="{{ $field }}" value="{{ old($field,$a00->{$field}?->format('Y-m-d')) }}"></div>@endforeach</div></section>
@php($editCustomerEvents=old('customer_events',$a00->resolvedCustomerEvents()) ?: [['name'=>'','date'=>null,'tba'=>false]])
<section class="edit-section"><h3>III. Schedule of Customer Events</h3><div class="edit-customer-events"><div id="editCustomerEventRows">@foreach($editCustomerEvents as $event)<div class="edit-customer-event-row"><span class="edit-event-number">{{ $loop->iteration }}.</span><div class="edit-field"><label>Nama Event *</label><input data-event-name name="customer_events[{{ $loop->index }}][name]" value="{{ $event['name'] ?? '' }}" placeholder="Contoh: DP, PP, MPP, PILOT, SOP" required></div><div class="edit-field"><label>Tanggal</label><input data-event-date type="date" name="customer_events[{{ $loop->index }}][date]" value="{{ $event['date'] ?? '' }}" @disabled(!empty($event['tba']))></div><label class="edit-event-tba"><input data-event-tba type="checkbox" name="customer_events[{{ $loop->index }}][tba]" value="1" @checked(!empty($event['tba']))> TBA</label><button class="edit-event-remove" type="button" aria-label="Hapus event">&times;</button></div>@endforeach</div><button class="edit-event-add" id="editAddCustomerEvent" type="button">+ Tambah Event</button></div></section>
<section class="edit-section"><h3>Penerbitan & Approval</h3><div class="edit-grid"><div class="edit-field"><label>Dibuat oleh — PIC Marketing</label><select name="prepared_by"><option value="">Pilih PIC Marketing</option>@foreach($picsMarketing as $pic)<option value="{{ $pic->name }}" @selected(old('prepared_by',$a00->prepared_by)===$pic->name)>{{ $pic->name }}</option>@endforeach</select></div><div class="edit-field"><label>Diketahui oleh — Div. Marketing</label><select name="acknowledged_by"><option value="">Pilih Div. Marketing</option>@foreach($picsDivMarketing as $pic)<option value="{{ $pic->name }}" @selected(old('acknowledged_by',$a00->acknowledged_by ?: 'L. Andri H.')===$pic->name)>{{ $pic->name }}</option>@endforeach</select></div><div class="edit-field"><label>Disetujui oleh — Director</label><select name="approved_by"><option value="">Pilih Director</option>@foreach($picsDirector as $pic)<option value="{{ $pic->name }}" @selected(old('approved_by',$a00->approved_by ?: 'Y. Susanto')===$pic->name)>{{ $pic->name }}</option>@endforeach</select></div><div class="edit-field"><label>Lokasi *</label><input name="issue_location" value="{{ old('issue_location',$a00->issue_location) }}" required></div><div class="edit-field span4"><label>Catatan</label><textarea name="notes">{{ old('notes',$a00->notes) }}</textarea></div></div></section>
<div class="edit-actions"><button type="button" class="edit-btn" onclick="{{ request()->boolean('embedded') ? 'parent.postMessage({type:\'a00-edit-cancel\'},location.origin)' : 'history.back()' }}">Batal</button><button class="edit-btn primary">Simpan Seluruh Perubahan</button></div></form></div>
<script>
const editCustomerEventRows=document.getElementById('editCustomerEventRows');
function refreshEditCustomerEvents(){const rows=[...editCustomerEventRows.querySelectorAll('.edit-customer-event-row')];rows.forEach((row,index)=>{row.querySelector('.edit-event-number').textContent=(index+1)+'.';row.querySelector('[data-event-name]').name=`customer_events[${index}][name]`;row.querySelector('[data-event-date]').name=`customer_events[${index}][date]`;row.querySelector('[data-event-tba]').name=`customer_events[${index}][tba]`;row.querySelector('.edit-event-remove').disabled=rows.length===1})}
function bindEditCustomerEvent(row){const tba=row.querySelector('[data-event-tba]'),date=row.querySelector('[data-event-date]');tba.addEventListener('change',()=>{date.disabled=tba.checked;if(tba.checked)date.value=''});row.querySelector('.edit-event-remove').addEventListener('click',()=>{if(editCustomerEventRows.children.length<=1)return;row.remove();refreshEditCustomerEvents()})}
[...editCustomerEventRows.querySelectorAll('.edit-customer-event-row')].forEach(bindEditCustomerEvent);
document.getElementById('editAddCustomerEvent').addEventListener('click',()=>{const row=document.createElement('div');row.className='edit-customer-event-row';row.innerHTML='<span class="edit-event-number"></span><div class="edit-field"><label>Nama Event *</label><input data-event-name placeholder="Contoh: DP, PP, MPP, PILOT, SOP" required></div><div class="edit-field"><label>Tanggal</label><input data-event-date type="date"></div><label class="edit-event-tba"><input data-event-tba type="checkbox" value="1"> TBA</label><button class="edit-event-remove" type="button" aria-label="Hapus event">&times;</button>';editCustomerEventRows.appendChild(row);bindEditCustomerEvent(row);refreshEditCustomerEvents();row.querySelector('[data-event-name]').focus()});
refreshEditCustomerEvents();
</script>
@endsection
