@extends('layouts.app')
@section('title','Edit Data Operasional')
@section('page-title','Edit Data Operasional Project')
@section('breadcrumb')A00 / {{ $a00->document_number }} / Edit Operasional@endsection
@section('content')
@if(request()->boolean('embedded'))<style>html,body{background:#f5f7fb!important}.sidebar,.sidebar-overlay,.header,.breadcrumb,.footer,.costing-assistant{display:none!important}.app-wrapper,.main-wrapper{display:block!important;margin:0!important;width:100%!important}.main-content{padding:18px!important}</style>@endif
<style>.op-card{max-width:760px;margin:0 auto;background:#fff;border:1px solid #dbe5f2;border-radius:12px;overflow:hidden;box-shadow:0 8px 25px rgba(15,23,42,.06)}.op-head{padding:1rem 1.15rem;background:#edf3fb}.op-head h3{margin:0 0 .25rem;color:#123b75;font-size:1rem}.op-head p{margin:0;color:#64748b;font-size:.72rem}.op-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem;padding:1.15rem}.op-field label{display:block;margin-bottom:.35rem;color:#475569;font-size:.7rem;font-weight:800}.op-field input,.op-field select{box-sizing:border-box;width:100%;height:38px;border:1px solid #cbd5e1;border-radius:7px;padding:0 .65rem;background:#fff}.op-note{margin:0 1.15rem 1rem;padding:.65rem .75rem;border-left:3px solid #2563eb;background:#eff6ff;color:#475569;font-size:.7rem}.op-actions{display:flex;justify-content:flex-end;gap:.5rem;padding:.85rem 1.15rem;border-top:1px solid #e2e8f0;background:#f8fafc}.op-btn{min-height:36px;padding:0 .85rem;border:1px solid #cbd5e1;border-radius:7px;background:#fff;color:#334155;font-weight:800;cursor:pointer}.op-btn.primary{border-color:#0b3478;background:#0b3478;color:#fff}.op-error{margin:1rem;padding:.7rem;background:#fee2e2;color:#991b1b;border-radius:8px}@media(max-width:600px){.op-grid{grid-template-columns:1fr}}</style>
<form class="op-card" method="POST" action="{{ route('control-project.a00.update-operational',$a00,absolute:false) }}">@csrf @method('PUT')@if(request()->boolean('embedded'))<input type="hidden" name="embedded" value="1">@endif
<div class="op-head"><h3>{{ $a00->document_number }}</h3><p>{{ $a00->formattedCustomerName() }} · {{ $a00->items->pluck('model')->filter()->unique()->join(', ') ?: $a00->model }}</p></div>
@if($errors->any())<div class="op-error">{{ $errors->first() }}</div>@endif
@php($revision=$a00->projectRevision)
<div class="op-grid"><div class="op-field"><label>Plant *</label><select name="plant_id" required><option value="">Pilih plant</option>@foreach($plants as $plant)<option value="{{ $plant->id }}" @selected((string)old('plant_id',$revision?->plant_id)===(string)$plant->id)>{{ $plant->code }} — {{ $plant->name }}</option>@endforeach</select></div><div class="op-field"><label>Periode *</label><input type="month" name="period" value="{{ old('period',$revision?->period) }}" required></div><div class="op-field"><label>PIC Engineering *</label><select name="pic_engineering" required><option value="">Pilih PIC Engineering</option>@foreach($picsEngineering as $pic)<option value="{{ $pic->name }}" @selected(old('pic_engineering',$revision?->pic_engineering)===$pic->name)>{{ $pic->name }}</option>@endforeach</select></div><div class="op-field"><label>PIC Marketing *</label><select name="pic_marketing" required><option value="">Pilih PIC Marketing</option>@foreach($picsMarketing as $pic)<option value="{{ $pic->name }}" @selected(old('pic_marketing',$revision?->pic_marketing)===$pic->name)>{{ $pic->name }}</option>@endforeach</select></div></div>
<div class="op-note">Perubahan ini berlaku untuk seluruh assembly pada A00 tersebut dan tidak mengubah dokumen New Project Declaration.</div>
<div class="op-actions"><button type="button" class="op-btn" onclick="{{ request()->boolean('embedded') ? 'parent.postMessage({type:\'a00-edit-cancel\'},location.origin)' : 'history.back()' }}">Batal</button><button class="op-btn primary">Simpan Perubahan</button></div></form>
@endsection
