@extends('layouts.app')
@section('title','A00 — New Project') @section('page-title','Control Project — A00')
@section('breadcrumb')<a href="{{ route('dashboard',absolute:false) }}">Dashboard</a> / A00 @endsection
@section('content')
<style>.a00-head{justify-content:flex-end}</style>
<style>
.a00-confirm{width:min(430px,calc(100vw - 32px));padding:0;border:0;border-radius:14px;box-shadow:0 24px 70px rgba(15,23,42,.3)}.a00-confirm::backdrop{background:rgba(15,23,42,.55)}.a00-confirm-head{display:flex;align-items:center;gap:10px;padding:16px 18px;border-bottom:1px solid #e2e8f0;color:#991b1b;font-size:14px;font-weight:850}.a00-confirm-icon{display:grid;width:32px;height:32px;place-items:center;border-radius:50%;background:#fee2e2;color:#dc2626;font-size:18px}.a00-confirm-body{padding:18px;color:#475569;font-size:12px;line-height:1.6}.a00-confirm-body strong{display:block;margin-bottom:5px;color:#0f172a;font-size:13px}.a00-confirm-foot{display:flex;justify-content:flex-end;gap:8px;padding:12px 18px;border-top:1px solid #e2e8f0;background:#f8fafc}.a00-confirm-btn{min-height:34px;padding:0 14px;border:1px solid #cbd5e1;border-radius:7px;background:#fff;color:#334155;font-size:11px;font-weight:800;cursor:pointer}.a00-confirm-btn.danger{border-color:#dc2626;background:#dc2626;color:#fff}
.a00-confirm{position:fixed;inset:50% auto auto 50%;margin:0;transform:translate(-50%,-50%)}
</style>
<style>.a00-head{display:flex;align-items:center;gap:7px;margin-bottom:12px}.a00-search{display:flex;gap:7px}.a00-input{width:290px;height:34px;box-sizing:border-box;border:1px solid #cbd8ea;border-radius:7px;padding:0 10px;font-size:11px}.a00-btn{display:inline-flex;min-height:32px;align-items:center;justify-content:center;padding:0 12px;border:0;border-radius:7px;background:#2864e8;color:#fff;font-size:10px;font-weight:800;text-decoration:none;cursor:pointer;white-space:nowrap}.a00-btn.secondary{border:1px solid #b9c9df;background:#fff;color:#17458e}.a00-card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}.a00-table{width:100%;border-collapse:collapse;font-size:.82rem}.a00-table th{background:#0b3478;color:#fff;text-align:left;padding:.75rem}.a00-table td{padding:.75rem;border-bottom:1px solid #edf2f7}.a00-table tr:hover{background:#f8fbff}.badge{padding:.25rem .55rem;border-radius:999px;background:#dbeafe;color:#1e40af;font-size:.7rem;font-weight:700}.a00-actions{display:flex;align-items:center;gap:.4rem}.a00-action-btn,.a00-actions>a{display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;min-height:29px;border:1px solid #cbd5e1;border-radius:6px;background:#fff;color:#0b3478;padding:.35rem .55rem;font-size:.7rem;font-weight:750;line-height:1;text-decoration:none;cursor:pointer;white-space:nowrap}.a00-action-btn.danger{border-color:#fecaca;color:#b91c1c}.a00-delete-form{margin:0}.a00-modal{border:0;padding:0;width:calc(100vw - 24px);height:calc(100vh - 24px);max-width:1280px;border-radius:15px;overflow:hidden;box-shadow:0 30px 80px rgba(15,23,42,.35);position:fixed;inset:auto;top:50%;left:50%;transform:translate(-50%,-50%);margin:0}.a00-modal::backdrop{background:rgba(15,23,42,.65)}.a00-modal-bar{box-sizing:border-box;height:48px;display:flex;align-items:center;justify-content:space-between;padding:0 1rem;background:#082d70;color:#fff}.a00-modal-close{width:30px;height:30px;border:0;border-radius:7px;background:rgba(255,255,255,.12);color:#fff;font-size:20px;cursor:pointer}.a00-modal iframe{display:block;width:100%;height:calc(100% - 48px);border:0;background:#f5f7fb}.a00-edit-modal{width:min(820px,calc(100vw - 28px));height:min(520px,calc(100vh - 28px))}@media(max-width:700px){.a00-head{align-items:stretch;flex-direction:column}.a00-search,.a00-input{width:100%}}</style>
<style>.a00-section-title{margin:16px 0 8px;color:#0f172a;font-size:13px}.a00-section-title.first{margin-top:0}.badge.waiting{background:#fff7ed;color:#c2410c}.source-label{display:block;margin-top:3px;color:#64748b;font-size:10px}</style>
<style>.a00-select{width:16px;height:16px;accent-color:#2563eb;cursor:pointer}.a00-btn:disabled{opacity:.48;cursor:not-allowed}.a00-selection-info{color:#64748b;font-size:10px;font-weight:700;white-space:nowrap}</style>
<style>.a00-tabs{display:grid;grid-template-columns:repeat(2,minmax(220px,360px));gap:10px;width:max-content;max-width:100%;margin-bottom:16px;padding:6px;border:1px solid #dbe5f2;border-radius:14px;background:rgba(255,255,255,.82);box-shadow:0 8px 24px rgba(15,23,42,.06)}.a00-tab{position:relative;display:grid;grid-template-columns:38px minmax(0,1fr) auto;align-items:center;gap:10px;min-height:58px;padding:8px 12px;border:1px solid transparent;border-radius:10px;color:#52647f;text-decoration:none;transition:transform .18s ease,box-shadow .18s ease,background .18s ease}.a00-tab:hover{background:#f8fbff;border-color:#dbeafe;transform:translateY(-1px)}.a00-tab.active{border-color:#1d4ed8;background:linear-gradient(135deg,#0b3478 0%,#2563eb 100%);color:#fff;box-shadow:0 8px 18px rgba(37,99,235,.24)}.a00-tab-icon{display:grid;width:38px;height:38px;place-items:center;border-radius:9px;background:#eaf2ff;color:#2563eb}.a00-tab.active .a00-tab-icon{background:rgba(255,255,255,.16);color:#fff}.a00-tab-icon svg{width:19px;height:19px}.a00-tab-copy{display:flex;min-width:0;flex-direction:column;line-height:1.25}.a00-tab-title{font-size:11px;font-weight:850}.a00-tab-description{margin-top:3px;color:#8493a9;font-size:9px;font-weight:650}.a00-tab.active .a00-tab-description{color:#dbeafe}.a00-tab-count{display:grid;min-width:27px;height:27px;place-items:center;padding:0 7px;border-radius:999px;background:#e2e8f0;color:#475569;font-size:10px;font-weight:850}.a00-tab.active .a00-tab-count{background:#fff;color:#1d4ed8}@media(max-width:720px){.a00-tabs{grid-template-columns:1fr;width:100%}.a00-tab{grid-template-columns:34px minmax(0,1fr) auto}.a00-tab-icon{width:34px;height:34px}}</style>
<style>.a00-panel{display:grid;grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"title actions" "table table" "pagination pagination";align-items:center;gap:10px 14px;padding:14px;border:1px solid #dbe5f2;border-radius:12px;background:#fff;box-shadow:0 10px 28px rgba(15,23,42,.04)}.a00-panel .a00-section-title{grid-area:title;margin:0;font-size:13px}.a00-panel .a00-head{grid-area:actions;margin:0}.a00-panel .a00-card{grid-area:table;border-color:#dbe5f2;border-radius:10px}.a00-panel .a00-table th{padding:.68rem;background:#f8fafc;border-bottom:1px solid #dbe5f2;color:#64748b;font-size:.63rem;text-transform:uppercase}.a00-panel .a00-table td{padding:.72rem .68rem;color:#334155;font-size:.72rem}.a00-panel>.a00-pagination{grid-area:pagination;margin-top:0!important}@media(max-width:760px){.a00-panel{grid-template-columns:1fr;grid-template-areas:"title" "actions" "table" "pagination"}.a00-panel .a00-head,.a00-panel .a00-search{width:100%}}</style>
@if(session('success'))<div style="padding:.75rem 1rem;background:#dcfce7;color:#166534;border-radius:8px;margin-bottom:1rem">{{ session('success') }}</div>@endif
<nav class="a00-tabs" aria-label="Daftar Control Project A00"><a class="a00-tab {{ $tab==='pending'?'active':'' }}" href="{{ route('control-project.a00.index',['tab'=>'pending'],false) }}"><span class="a00-tab-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span><span class="a00-tab-copy"><span class="a00-tab-title">Menunggu Pembuatan A00</span><span class="a00-tab-description">Project baru yang perlu diterbitkan</span></span><span class="a00-tab-count">{{ $pendingProjects->total() }}</span></a><a class="a00-tab {{ $tab==='issued'?'active':'' }}" href="{{ route('control-project.a00.index',['tab'=>'issued'],false) }}"><span class="a00-tab-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M7 3h7l4 4v14H7z"/><path d="M14 3v5h5"/><path d="m10 15 2 2 4-5"/></svg></span><span class="a00-tab-copy"><span class="a00-tab-title">A00 Sudah Diterbitkan</span><span class="a00-tab-description">Dokumen A00 yang telah terbit</span></span><span class="a00-tab-count">{{ $forms->total() }}</span></a></nav>
<section class="a00-panel">
<div class="a00-head"><button type="button" class="a00-btn secondary" onclick="openA00Modal()">+ Buat A00</button>@if($tab==='pending')<button type="button" class="a00-btn" id="createCombinedA00" disabled>Buat A00 Gabungan</button><span class="a00-selection-info" id="a00SelectionInfo">0 project dipilih</span>@endif<form class="a00-search"><input type="hidden" name="tab" value="{{ $tab }}"><input class="a00-input" name="q" value="{{ request('q') }}" placeholder="Cari nomor, customer, model..."><button class="a00-btn">Cari</button>@if(request('q'))<a class="a00-btn secondary" href="{{ route('control-project.a00.index',['tab'=>$tab],false) }}">Reset</a>@endif</form></div>
@if($tab==='pending')
<h3 class="a00-section-title first">Project Menunggu Pembuatan A00</h3>
<div class="a00-card"><table class="a00-table"><thead><tr><th style="width:34px"><input class="a00-select" id="selectAllPending" type="checkbox" aria-label="Pilih semua project"></th><th>Sumber</th><th>Diterima</th><th>Customer</th><th>Model</th><th>Assembly</th><th>Progress</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($pendingProjects as $project)
@php
    $revision=$project->revisions->first();
    $sourceTask=$project->workflowTasks->first(fn($task)=>in_array(data_get($task->metadata,'source'),['manual_drawing_registration','manual_breakdown','new_project_draft'],true));
    $source=match(data_get($sourceTask?->metadata,'source')) {
        'manual_breakdown' => '+ Breakdown',
        'new_project_draft' => '+ Project Baru',
        default => '+ Registrasi Drawing',
    };
@endphp
<tr><td><input class="a00-select pending-project-select" type="checkbox" value="{{ $project->id }}" data-customer="{{ mb_strtolower(trim($project->customer)) }}" data-category="{{ $project->product?->code }}" aria-label="Pilih {{ $project->part_number }}"></td><td><strong>{{ $source }}</strong><span class="source-label">{{ $project->product?->name ?: '-' }}</span></td><td>{{ optional($revision?->received_date)->format('d M Y') ?: optional($project->created_at)->format('d M Y') }}</td><td>{{ $project->customer }}</td><td>{{ $project->model }}</td><td><strong>{{ $project->part_number }}</strong><span class="source-label">{{ $project->part_name }}</span></td><td><x-project-progress :revision="$revision" /></td><td><span class="badge waiting">Menunggu A00</span></td><td><button type="button" class="a00-action-btn" data-url="{{ route('control-project.a00.create',['embedded'=>1,'project_id'=>$project->id],false) }}" onclick="openA00Modal(this.dataset.url)">Buat A00</button></td></tr>
@empty<tr><td colspan="9" style="text-align:center;padding:1.4rem;color:#64748b">Belum ada project dari Registrasi Drawing atau Breakdown yang menunggu A00.</td></tr>@endforelse
</tbody></table></div><div class="a00-pagination" style="margin-top:1rem">{{ $pendingProjects->links() }}</div>
@else
<h3 class="a00-section-title">A00 yang Sudah Diterbitkan</h3>
<div class="a00-card"><table class="a00-table"><thead><tr><th>Tanggal</th><th>Customer</th><th>Model</th><th>Assembly</th><th>Nomor A00</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($forms as $form)<tr><td>{{ $form->document_date->format('d M Y') }}</td><td>{{ $form->formattedCustomerName() }}</td><td>{{ $form->items->pluck('model')->filter()->unique()->join(', ') ?: $form->model }}</td><td>{{ $form->items->count() ?: 1 }} Assembly<br><small>{{ $form->items->pluck('assy_number')->take(3)->join(', ') ?: $form->assy_number }}</small></td><td><strong>{{ $form->document_number }}</strong><br><small>Rev. {{ $form->revision }}</small></td><td><span class="badge">A00 Issued</span></td><td><div class="a00-actions"><button type="button" class="a00-action-btn" data-url="{{ route('control-project.a00.edit',['a00'=>$form,'embedded'=>1],false) }}" data-number="{{ $form->document_number }}" onclick="openA00Edit(this.dataset)">Edit A00</button><a href="{{ route('control-project.a00.show',$form,absolute:false) }}">Lihat</a><form class="a00-delete-form" method="POST" action="{{ route('control-project.a00.destroy',$form,absolute:false) }}" onsubmit="return confirm('Yakin ingin menghapus A00 {{ addslashes($form->document_number) }} beserta seluruh workflow terkait? Data yang dihapus tidak dapat dikembalikan.')">@csrf @method('DELETE')<button class="a00-action-btn danger" type="submit">Hapus</button></form></div></td></tr>
@empty<tr><td colspan="7" style="text-align:center;padding:2rem;color:#64748b">Belum ada A00.</td></tr>@endforelse
</tbody></table></div><div class="a00-pagination" style="margin-top:1rem">{{ $forms->links() }}</div>
@endif
</section>
<dialog class="a00-modal" id="a00CreateModal"><div class="a00-modal-bar"><strong>Buat A00 — New Project Declaration</strong><button class="a00-modal-close" onclick="closeA00Modal()" aria-label="Tutup">&times;</button></div><iframe id="a00CreateFrame" title="Form Buat A00"></iframe></dialog>
<dialog class="a00-modal" id="a00EditModal"><div class="a00-modal-bar"><strong id="a00EditTitle">Edit A00 — New Project Declaration</strong><button class="a00-modal-close" onclick="closeA00Edit()" aria-label="Tutup">&times;</button></div><iframe id="a00EditFrame" title="Edit A00 New Project Declaration"></iframe></dialog>
<dialog class="a00-confirm" id="a00DeleteModal"><div class="a00-confirm-head"><span class="a00-confirm-icon">!</span><span>Konfirmasi Hapus A00</span></div><div class="a00-confirm-body"><strong id="a00DeleteNumber"></strong><span>A00 beserta seluruh project dan workflow terkait akan dihapus permanen. Data yang sudah dihapus tidak dapat dikembalikan.</span></div><div class="a00-confirm-foot"><button class="a00-confirm-btn" id="cancelA00Delete" type="button">Batal</button><button class="a00-confirm-btn danger" id="confirmA00Delete" type="button">Ya, Hapus</button></div></dialog>
<script>
const a00Modal=document.getElementById('a00CreateModal'),a00Frame=document.getElementById('a00CreateFrame'),a00EditModal=document.getElementById('a00EditModal'),a00EditFrame=document.getElementById('a00EditFrame');
function openA00Modal(url=null){const target=url||@json(route('control-project.a00.create',['embedded'=>1],false));if(a00Frame.src!==new URL(target,location.origin).href)a00Frame.src=target;a00Modal.showModal()}
function closeA00Modal(){a00Modal.close()}
const pendingProjectSelects=[...document.querySelectorAll('.pending-project-select')];
const combinedA00Button=document.getElementById('createCombinedA00');
const selectionInfo=document.getElementById('a00SelectionInfo');
const selectAllPending=document.getElementById('selectAllPending');
function selectedPendingProjects(){return pendingProjectSelects.filter(input=>input.checked)}
function refreshA00Selection(){
 const selected=selectedPendingProjects();
 if(selectionInfo)selectionInfo.textContent=selected.length+' project dipilih';
 if(combinedA00Button)combinedA00Button.disabled=selected.length<2;
 if(selectAllPending){selectAllPending.checked=pendingProjectSelects.length>0&&selected.length===pendingProjectSelects.length;selectAllPending.indeterminate=selected.length>0&&selected.length<pendingProjectSelects.length}
}
pendingProjectSelects.forEach(input=>input.addEventListener('change',refreshA00Selection));
selectAllPending?.addEventListener('change',()=>{pendingProjectSelects.forEach(input=>input.checked=selectAllPending.checked);refreshA00Selection()});
combinedA00Button?.addEventListener('click',()=>{
 const selected=selectedPendingProjects();
 if(selected.length<2)return;
 const customers=[...new Set(selected.map(input=>input.dataset.customer))];
 const categories=[...new Set(selected.map(input=>input.dataset.category))];
 if(customers.length>1){alert('Project gabungan harus memiliki customer yang sama.');return}
 if(categories.length>1){alert('Project gabungan harus memiliki Business Category yang sama.');return}
 const target=new URL(@json(route('control-project.a00.create',absolute:false)),location.origin);
 target.searchParams.set('embedded','1');
 selected.forEach(input=>target.searchParams.append('project_ids[]',input.value));
 openA00Modal(target.toString());
});
function openA00Edit(data){a00EditFrame.src=data.url;document.getElementById('a00EditTitle').textContent='Edit A00 — '+data.number;a00EditModal.showModal()}
function closeA00Edit(){a00EditModal.close();a00EditFrame.src=''}
const a00DeleteModal=document.getElementById('a00DeleteModal'),a00DeleteNumber=document.getElementById('a00DeleteNumber');let pendingA00DeleteForm=null;
document.querySelectorAll('.a00-delete-form').forEach(form=>{form.removeAttribute('onsubmit');form.addEventListener('submit',event=>{event.preventDefault();pendingA00DeleteForm=form;const number=form.closest('tr').querySelector('td strong')?.textContent?.trim()||'A00 ini';a00DeleteNumber.textContent=number;a00DeleteModal.showModal()})});
document.getElementById('cancelA00Delete').addEventListener('click',()=>{pendingA00DeleteForm=null;a00DeleteModal.close()});
document.getElementById('confirmA00Delete').addEventListener('click',()=>{if(!pendingA00DeleteForm)return;const form=pendingA00DeleteForm;pendingA00DeleteForm=null;a00DeleteModal.close();form.submit()});
a00DeleteModal.addEventListener('click',event=>{if(event.target===a00DeleteModal){pendingA00DeleteForm=null;a00DeleteModal.close()}});
a00DeleteModal.addEventListener('close',()=>{pendingA00DeleteForm=null});
window.addEventListener('message',event=>{if(event.origin!==location.origin)return;if(event.data?.type==='a00-cancel')closeA00Modal();if(event.data?.type==='a00-created'&&event.data.url){closeA00Modal();location.href=event.data.url}if(event.data?.type==='a00-edit-cancel')closeA00Edit();if(event.data?.type==='a00-updated'){closeA00Edit();location.reload()}});
</script>
@endsection
