@extends('layouts.app')
@section('title','A00 — New Project') @section('page-title','Control Project — A00')
@section('breadcrumb')<a href="{{ route('dashboard',absolute:false) }}">Dashboard</a> / A00 @endsection
@section('content')
<style>.a00-modal{width:calc(100vw - 24px)!important;height:calc(100vh - 24px)!important;max-width:1280px!important;max-height:none!important}.a00-modal iframe{height:calc(100% - 48px)!important}</style>
<style>.a00-head{display:flex;justify-content:space-between;gap:1rem;margin-bottom:1rem}.a00-search{display:flex;gap:.5rem}.a00-input{border:1px solid #cbd5e1;border-radius:8px;padding:.6rem .75rem;font:inherit}.a00-btn{border:0;border-radius:8px;background:#0b3478;color:#fff;padding:.65rem 1rem;font-weight:700;text-decoration:none;cursor:pointer}.a00-card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}.a00-table{width:100%;border-collapse:collapse;font-size:.82rem}.a00-table th{background:#0b3478;color:#fff;text-align:left;padding:.75rem}.a00-table td{padding:.75rem;border-bottom:1px solid #edf2f7}.a00-table tr:hover{background:#f8fbff}.badge{padding:.25rem .55rem;border-radius:999px;background:#dbeafe;color:#1e40af;font-size:.7rem;font-weight:700}.a00-modal{border:0;padding:0;width:min(1160px,96vw);height:94vh;max-height:900px;border-radius:15px;overflow:hidden;box-shadow:0 30px 80px rgba(15,23,42,.35);position:fixed;inset:auto;top:50%;left:50%;transform:translate(-50%,-50%);margin:0}.a00-modal::backdrop{background:rgba(15,23,42,.65)}.a00-modal-bar{height:48px;display:flex;align-items:center;justify-content:space-between;padding:0 1rem;background:#082d70;color:#fff}.a00-modal-close{width:30px;height:30px;border:0;border-radius:7px;background:rgba(255,255,255,.12);color:#fff;font-size:20px;cursor:pointer}.a00-modal iframe{display:block;width:100%;height:calc(100% - 48px);border:0;background:#f5f7fb}</style>
@if(session('success'))<div style="padding:.75rem 1rem;background:#dcfce7;color:#166534;border-radius:8px;margin-bottom:1rem">{{ session('success') }}</div>@endif
<div class="a00-head"><form class="a00-search"><input class="a00-input" name="q" value="{{ request('q') }}" placeholder="Cari nomor, customer, model..."><button class="a00-btn">Cari</button></form><button type="button" class="a00-btn" onclick="openA00Modal()">+ Buat A00</button></div>
<div class="a00-card"><table class="a00-table"><thead><tr><th>Nomor A00</th><th>Tanggal</th><th>Customer</th><th>Model</th><th>Assembly</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($forms as $form)<tr><td><strong>{{ $form->document_number }}</strong><br><small>Rev. {{ $form->revision }}</small></td><td>{{ $form->document_date->format('d M Y') }}</td><td>{{ $form->customer }}</td><td>{{ $form->items->pluck('model')->filter()->unique()->join(', ') ?: $form->model }}</td><td>{{ $form->items->count() ?: 1 }} assembly<br><small>{{ $form->items->pluck('assy_number')->take(3)->join(', ') ?: $form->assy_number }}</small></td><td><span class="badge">A00 Issued</span></td><td><a href="{{ route('control-project.a00.show',$form,absolute:false) }}">Lihat</a></td></tr>
@empty<tr><td colspan="7" style="text-align:center;padding:2rem;color:#64748b">Belum ada A00.</td></tr>@endforelse
</tbody></table></div><div style="margin-top:1rem">{{ $forms->links() }}</div>
<dialog class="a00-modal" id="a00CreateModal"><div class="a00-modal-bar"><strong>Buat A00 — New Project Declaration</strong><button class="a00-modal-close" onclick="closeA00Modal()" aria-label="Tutup">&times;</button></div><iframe id="a00CreateFrame" title="Form Buat A00"></iframe></dialog>
<script>
const a00Modal=document.getElementById('a00CreateModal'),a00Frame=document.getElementById('a00CreateFrame');
function openA00Modal(){if(!a00Frame.src)a00Frame.src=@json(route('control-project.a00.create',['embedded'=>1],false));a00Modal.showModal()}
function closeA00Modal(){a00Modal.close()}
window.addEventListener('message',event=>{if(event.origin!==location.origin)return;if(event.data?.type==='a00-cancel')closeA00Modal();if(event.data?.type==='a00-created'){closeA00Modal();location.reload()}});
</script>
@endsection
