@extends('layouts.app')
@section('title','Inbox Breakdown')
@section('page-title','Breakdown Material')
@section('breadcrumb')<a href="{{ route('dashboard',absolute:false) }}">Dashboard</a><span class="breadcrumb-separator">/</span><span>Inbox Breakdown</span>@endsection
@section('content')
<style>
    .file-picker { width: 250px !important; max-width: 250px; }
    .file-picker-name { flex: 1 1 auto; min-width: 0; overflow: visible; text-overflow: clip; white-space: nowrap; font-size: .62rem; }
</style>
<style>.breakdown-card{background:#fff;border:1px solid #dbe5f2;border-radius:11px;padding:1rem}.breakdown-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:.8rem}.breakdown-head h3{margin:0;font-size:1rem}.breakdown-search{display:flex;gap:.45rem}.breakdown-search input{width:310px;height:34px;border:1px solid #cbd5e1;border-radius:8px;padding:0 .7rem}.breakdown-filters{display:flex;gap:.4rem;margin:0 0 .8rem}.breakdown-filter{padding:.38rem .75rem;border:1px solid #cbd5e1;border-radius:999px;background:#fff;color:#475569;font-size:.65rem;font-weight:800;text-decoration:none}.breakdown-filter.active{border-color:#2563eb;background:#2563eb;color:#fff}.breakdown-btn{display:inline-flex;align-items:center;justify-content:center;min-height:30px;padding:0 .65rem;border:1px solid #2563eb;border-radius:7px;background:#2563eb;color:#fff;font-size:.64rem;font-weight:800;text-decoration:none;cursor:pointer;white-space:nowrap}.breakdown-btn.secondary{border-color:#16a34a;background:#16a34a}.breakdown-table-wrap{overflow:auto;border:1px solid #dbe5f2;border-radius:10px}.breakdown-table{width:100%;min-width:1280px;border-collapse:collapse}.breakdown-table th{padding:.55rem .58rem;background:#f8fafc;border-bottom:1px solid #dbe5f2;color:#64748b;font-size:.58rem;text-align:left;text-transform:uppercase}.breakdown-table td{padding:.5rem .58rem;border-bottom:1px solid #e2e8f0;color:#334155;font-size:.68rem;vertical-align:middle}.project-name{display:grid;gap:.1rem}.project-name small{color:#64748b;font-size:.59rem}.task-status{display:inline-flex;padding:.2rem .42rem;border-radius:999px;background:#fff7ed;color:#c2410c;font-size:.57rem;font-weight:800;white-space:nowrap}.task-status.completed{background:#dcfce7;color:#15803d}.file-picker{display:flex;width:155px;height:28px;align-items:center;overflow:hidden;border:1px solid #cbd5e1;border-radius:6px;background:#fff;cursor:pointer}.file-picker:hover{border-color:#2563eb}.file-picker input{position:absolute;width:1px;height:1px;opacity:0;pointer-events:none}.file-picker-button{align-self:stretch;display:flex;align-items:center;padding:0 .42rem;background:#eff6ff;color:#1d4ed8;font-size:.56rem;font-weight:850;white-space:nowrap}.file-picker-name{min-width:0;overflow:hidden;padding:0 .38rem;color:#64748b;font-size:.56rem;text-overflow:ellipsis;white-space:nowrap}.action-stack{display:flex;gap:.35rem}.empty{text-align:center!important;padding:2rem!important;color:#64748b!important}</style>
@if(session('success'))<div style="margin-bottom:1rem;padding:.8rem 1rem;border:1px solid #86efac;border-radius:9px;background:#f0fdf4;color:#166534;font-size:.75rem;font-weight:700">{{ session('success') }}</div>@endif
@if($errors->any())<div style="margin-bottom:1rem;padding:.8rem 1rem;border:1px solid #fca5a5;border-radius:9px;background:#fef2f2;color:#991b1b;font-size:.75rem;font-weight:700">{{ $errors->first() }}</div>@endif
<div class="breakdown-card"><div class="breakdown-head"><div><h3>Inbox Breakdown</h3><small style="color:#64748b">Task masuk otomatis setelah distribusi drawing selesai.</small></div><form class="breakdown-search"><input type="hidden" name="status" value="{{ $filter }}"><input name="q" value="{{ $search }}" placeholder="Cari customer, model, atau part..."><button class="breakdown-btn">Cari</button></form></div><div class="breakdown-filters"><a class="breakdown-filter {{ $filter === 'active' ? 'active' : '' }}" href="{{ route('breakdown.inbox', ['status' => 'active', 'q' => $search ?: null], false) }}">Aktif</a><a class="breakdown-filter {{ $filter === 'history' ? 'active' : '' }}" href="{{ route('breakdown.inbox', ['status' => 'history', 'q' => $search ?: null], false) }}">History</a><a class="breakdown-filter {{ $filter === 'all' ? 'active' : '' }}" href="{{ route('breakdown.inbox', ['status' => 'all', 'q' => $search ?: null], false) }}">Semua</a></div><div class="breakdown-table-wrap"><table class="breakdown-table"><thead><tr><th>Project</th><th>Customer</th><th>Model</th><th>Part Number</th><th>Revision</th><th>Registrasi</th><th>Diterima</th><th>Status</th><th>Partlist</th><th>UMH</th><th>Aksi</th></tr></thead><tbody>
@forelse($tasks as $task)@php($hasPartlist=filled($task->revision->partlist_file_path))@php($hasUmh=filled($task->revision->umh_file_path))@php($isCompleted=$task->status === \App\Models\ProjectWorkflowTask::STATUS_COMPLETED)@php($formId='breakdown-upload-'.$task->id)<tr><td><div class="project-name"><strong>{{ $task->project->part_name }}</strong><small>{{ $task->project->product->name ?? '-' }}</small></div></td><td>{{ $task->project->customer }}</td><td>{{ $task->project->model }}</td><td><strong>{{ $task->project->part_number }}</strong></td><td>{{ $task->revision->version_label }}</td><td>{{ data_get($task->metadata,'registration_no','-') }}</td><td>{{ optional($task->available_at)->format('d/m/Y H:i') }}</td><td><span class="task-status {{ $isCompleted ? 'completed' : '' }}">{{ $isCompleted ? 'Selesai' : ($hasPartlist ? ($hasUmh ? 'Lengkap' : 'Menunggu UMH') : ($hasUmh ? 'Menunggu Partlist' : 'Menunggu Dokumen')) }}</span></td><td>@if($isCompleted)<span>{{ $task->revision->partlist_original_name ?: 'Belum ada' }}</span>@else<label class="file-picker"><input form="{{ $formId }}" type="file" name="partlist_file" accept=".xls,.xlsx,.pdf"><span class="file-picker-button">{{ $hasPartlist ? 'Ganti' : 'Pilih' }}</span><span class="file-picker-name" @if($hasPartlist) style="color:#166534" @endif>{{ $task->revision->partlist_original_name ?: 'Belum ada' }}</span></label>@endif</td><td>@if($isCompleted)<span>{{ $task->revision->umh_original_name ?: 'Belum ada' }}</span>@else<label class="file-picker"><input form="{{ $formId }}" type="file" name="umh_file" accept=".xls,.xlsx,.pdf"><span class="file-picker-button">{{ $hasUmh ? 'Ganti' : 'Pilih' }}</span><span class="file-picker-name" @if($hasUmh) style="color:#166534" @endif>{{ $task->revision->umh_original_name ?: 'Belum ada' }}</span></label>@endif</td><td>@if($isCompleted)<span style="color:#64748b">Selesai {{ optional($task->completed_at)->format('d/m/Y H:i') }}</span>@else<div class="action-stack"><form id="{{ $formId }}" method="POST" enctype="multipart/form-data" action="{{ route('breakdown.tasks.complete',$task,absolute:false) }}">@csrf<button class="breakdown-btn" title="Simpan dokumen Breakdown">Simpan</button></form>@if($hasPartlist)<form method="POST" action="{{ route('breakdown.tasks.start-costing',$task,absolute:false) }}">@csrf<button class="breakdown-btn secondary" title="Buka Form Costing">Form Costing</button></form>@endif</div>@endif</td></tr>@empty<tr><td colspan="11" class="empty">Tidak ada task Breakdown pada filter ini.</td></tr>@endforelse
</tbody></table></div><div style="margin-top:.8rem">{{ $tasks->links() }}</div></div>
<script>document.querySelectorAll('.file-picker').forEach(picker=>{const input=picker.querySelector('input');const name=picker.querySelector('.file-picker-name');const setName=value=>{name.textContent=value;name.title=value};setName(name.textContent.trim());input.addEventListener('change',()=>{setName(input.files?.[0]?.name||'Belum ada file');name.style.color=input.files?.length?'#0f172a':'#64748b'})});</script>
@endsection
