@extends('layouts.app')
@section('title','UAT Feedback') @section('page-title','UAT Feedback')
@section('breadcrumb')<a href="{{ route('dashboard',absolute:false) }}">Dashboard</a><span class="breadcrumb-separator">/</span><span>UAT Feedback</span>@endsection
@section('content')
<div class="uat-page">@if(session('success'))<div class="uat-flash">{{ session('success') }}</div>@endif
<section class="uat-hero"><div><span>USER ACCEPTANCE TESTING</span><h2>Masukan Pengguna</h2><p>Tinjau bug, kendala penggunaan, masalah data, dan saran dari pengguna aplikasi.</p></div><div class="uat-counts"><b>{{ $counts->sum() }}</b><span>Total</span><b>{{ $counts['open']??0 }}</b><span>Open</span><b>{{ $counts['in_progress']??0 }}</b><span>Diproses</span></div></section>
<nav class="uat-filters">@foreach(['all'=>'Semua','open'=>'Open','in_progress'=>'Diproses','resolved'=>'Selesai','rejected'=>'Ditolak'] as $key=>$label)<a class="{{ $status===$key?'active':'' }}" href="{{ route('uat-feedback.index',$key==='all'?[]:['status'=>$key],false) }}">{{ $label }}</a>@endforeach</nav>
<div class="uat-list">@forelse($feedback as $item)<article class="uat-ticket severity-{{ $item->severity }}"><header><div><span>{{ strtoupper($item->category) }} · {{ strtoupper($item->severity) }}</span><h3>#{{ $item->id }} {{ $item->title }}</h3><p>{{ $item->user->name }} · {{ $item->created_at->format('d M Y H:i') }}</p></div><b>{{ str_replace('_',' ',strtoupper($item->status)) }}</b></header><p class="uat-description">{{ $item->description }}</p><div class="uat-context">@if($item->page_url)<a href="{{ $item->page_url }}" target="_blank" rel="noopener">Buka halaman terkait</a>@endif<span>{{ $item->route_name?:'-' }}</span>@if($item->screenshot_path)<a href="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($item->screenshot_path) }}" target="_blank" rel="noopener">Lihat Screenshot</a>@endif</div><details><summary>Update Status</summary><form method="POST" action="{{ route('uat-feedback.update',$item,false) }}">@csrf @method('PATCH')<select name="status"><option value="open" @selected($item->status==='open')>Open</option><option value="in_progress" @selected($item->status==='in_progress')>Diproses</option><option value="resolved" @selected($item->status==='resolved')>Selesai</option><option value="rejected" @selected($item->status==='rejected')>Ditolak</option></select><textarea name="resolution_notes" rows="2" placeholder="Catatan penyelesaian...">{{ $item->resolution_notes }}</textarea><button>Simpan</button></form></details></article>@empty<div class="uat-empty">Belum ada feedback pada kategori ini.</div>@endforelse</div>{{ $feedback->links() }}</div>
<style>.uat-page{max-width:1250px;margin:auto;color:#193653}.uat-flash{margin-bottom:10px;padding:10px;border-radius:8px;background:#eafff2;color:#18713f;font-size:10px;font-weight:800}.uat-hero{display:flex;align-items:center;justify-content:space-between;padding:24px 27px;border-radius:15px;background:linear-gradient(120deg,#073d84,#0875ea);color:#fff}.uat-hero>div>span{color:#bfdbfe;font-size:9px;font-weight:900;letter-spacing:.13em}.uat-hero h2{margin:5px 0;font-size:22px}.uat-hero p{margin:0;color:#dbeafe;font-size:11px}.uat-counts{display:grid;grid-template-columns:auto auto;gap:3px 9px;padding:11px 15px;border:1px solid rgba(255,255,255,.25);border-radius:10px}.uat-counts b{font-size:13px}.uat-counts span{font-size:9px;color:#dbeafe}.uat-filters{display:flex;gap:7px;margin:13px 0}.uat-filters a{padding:7px 10px;border:1px solid #d4e0eb;border-radius:8px;background:#fff;color:#567088;font-size:9px;font-weight:800;text-decoration:none}.uat-filters a.active{border-color:#1672d7;background:#eaf4ff;color:#1264bd}.uat-list{display:grid;gap:9px}.uat-ticket{padding:14px 16px;border:1px solid #dbe5ef;border-left:4px solid #60a5fa;border-radius:11px;background:#fff}.uat-ticket.severity-critical{border-left-color:#dc2626}.uat-ticket.severity-high{border-left-color:#f97316}.uat-ticket header{display:flex;justify-content:space-between}.uat-ticket header span{color:#0d6dcd;font-size:8px;font-weight:900}.uat-ticket h3{margin:4px 0;font-size:13px}.uat-ticket header p,.uat-description{margin:0;color:#718398;font-size:9px}.uat-ticket header>b{font-size:9px}.uat-description{margin-top:10px;font-size:11px;line-height:1.55}.uat-context{display:flex;gap:8px;margin-top:10px}.uat-context a,.uat-context span{padding:4px 6px;border-radius:5px;background:#edf4fb;color:#32618d;font-size:8px;text-decoration:none}.uat-ticket details{margin-top:10px}.uat-ticket summary{cursor:pointer;font-size:9px;font-weight:800}.uat-ticket details form{display:grid;grid-template-columns:150px 1fr auto;gap:7px;margin-top:7px}.uat-ticket select,.uat-ticket textarea{padding:7px;border:1px solid #cedae6;border-radius:6px;font-size:9px}.uat-ticket button{border:0;border-radius:6px;background:#0870df;color:#fff;font-size:9px;font-weight:800}.uat-empty{padding:50px;border:1px dashed #c9d7e5;border-radius:11px;background:#fff;text-align:center;color:#7b8da0;font-size:11px}@media(max-width:700px){.uat-hero{align-items:flex-start;flex-direction:column;gap:12px}.uat-ticket details form{grid-template-columns:1fr}.uat-context{flex-wrap:wrap}}</style>
@endsection
