@extends('layouts.app')
@section('title', 'Inbox Costing')
@section('page-title', 'Inbox Costing')
@section('breadcrumb')<a href="{{ route('dashboard', absolute:false) }}">Dashboard</a><span class="breadcrumb-separator">/</span><span>Inbox Costing</span>@endsection

@section('content')
<style>
.ci-card{background:#fff;border:1px solid #d8e2ef;border-radius:12px;padding:16px}.ci-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:13px}.ci-head h3{margin:0 0 4px;color:#0f172a;font-size:15px}.ci-head p{margin:0;color:#64748b;font-size:11px}.ci-search{display:flex;gap:7px}.ci-search input,.ci-search select{height:34px;border:1px solid #cbd8ea;border-radius:7px;padding:0 10px;font-size:11px;background:#fff}.ci-search input{width:260px}.ci-btn{display:inline-flex;align-items:center;justify-content:center;min-height:31px;border:0;border-radius:7px;padding:0 12px;background:#2864e8;color:#fff;font-size:10px;font-weight:800;text-decoration:none;cursor:pointer}.ci-btn.secondary{border:1px solid #b9c9df;background:#fff;color:#17458e}.ci-btn.success{background:#16a34a}.ci-tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}.ci-tab{padding:6px 10px;border:1px solid #d6e0ed;border-radius:999px;color:#52647c;text-decoration:none;font-size:10px;font-weight:700}.ci-tab.active{border-color:#2864e8;background:#eaf1ff;color:#1d4ed8}.ci-wrap{overflow:auto;border:1px solid #d8e2ef;border-radius:9px}.ci-table{width:100%;min-width:1320px;border-collapse:collapse;font-size:10px}.ci-table th{padding:9px 10px;background:#f5f8fc;color:#52647c;text-align:left;text-transform:uppercase;font-size:8px;white-space:nowrap}.ci-table td{padding:10px;border-top:1px solid #e1e8f1;color:#334155;vertical-align:middle}.ci-table th:nth-child(2),.ci-table td:nth-child(2){width:175px;white-space:nowrap}.ci-table th:nth-child(4),.ci-table td:nth-child(4){width:120px;white-space:nowrap}.ci-table th:nth-child(7),.ci-table td:nth-child(7){width:285px}.ci-table th:nth-child(8),.ci-table td:nth-child(8){width:85px;white-space:nowrap}.ci-table th:nth-child(9),.ci-table td:nth-child(9){width:90px;white-space:nowrap}.ci-table th:nth-child(10),.ci-table td:nth-child(10){width:350px}.ci-table strong{color:#0f172a}.ci-table small{display:block;margin-top:3px;color:#718198}.ci-status{display:inline-flex;border-radius:999px;padding:5px 8px;font-size:9px;font-weight:800;white-space:nowrap}.ci-status.info{background:#eaf1ff;color:#1d4ed8}.ci-status.warning{background:#fff4dc;color:#b45309}.ci-status.danger{background:#fee8e8;color:#b91c1c}.ci-status.success{background:#e2f8e8;color:#15803d}.ci-actions{display:flex;gap:5px;flex-wrap:wrap}.ci-empty{text-align:center;padding:30px!important;color:#718198!important}.ci-pagination{margin-top:12px}.ci-note{margin-top:4px;color:#b45309;font-size:9px;font-weight:700}@media(max-width:800px){.ci-head{display:block}.ci-search{margin-top:10px}.ci-search input{width:100%}}
.ci-btn.revision{background:#7c3aed}.ci-flash{margin-bottom:12px;padding:9px 12px;border:1px solid #86efac;border-radius:8px;background:#f0fdf4;color:#166534;font-size:11px;font-weight:700}.ci-revision-modal{position:fixed;inset:0;width:min(560px,calc(100vw - 28px));max-height:calc(100vh - 28px);margin:auto;padding:0;border:0;border-radius:14px;overflow:auto;background:#fff;box-shadow:0 24px 70px rgba(15,23,42,.34)}.ci-revision-modal::backdrop{background:rgba(15,23,42,.55);backdrop-filter:blur(2px)}.ci-revision-head{display:flex;align-items:flex-start;justify-content:space-between;padding:14px 16px;background:linear-gradient(135deg,#0b3478,#7c3aed);color:#fff}.ci-revision-head button{border:0;background:transparent;color:#fff;font-size:20px;cursor:pointer}.ci-revision-body{display:grid;gap:12px;padding:16px}.ci-revision-field label{display:block;margin-bottom:5px;color:#475569;font-size:11px;font-weight:800}.ci-revision-field select,.ci-revision-field input,.ci-revision-field textarea{box-sizing:border-box;width:100%;border:1px solid #cbd5e1;border-radius:8px;padding:9px;font-size:11px}.ci-revision-field textarea{min-height:75px}.ci-revision-foot{display:flex;justify-content:flex-end;gap:7px;padding:12px 16px;border-top:1px solid #e2e8f0;background:#f8fafc}
.ci-comment{margin-top:5px;padding:6px 7px;border-left:3px solid #8b5cf6;border-radius:5px;background:#f5f3ff;color:#5b21b6;font-size:9px}.ci-comment strong{display:block;color:#4c1d95}
.ci-member{display:flex;min-height:32px;align-items:center;padding:5px 0}.ci-member+.ci-member{border-top:1px dashed #d8e2ef}.ci-member.stack{align-items:flex-start}.ci-member.update{box-sizing:border-box;flex-direction:column;align-items:flex-start;justify-content:center;line-height:1.25}.ci-member.update small{margin-top:3px}.ci-member .ci-actions{align-items:center}.ci-actions.grouped{align-items:stretch;flex-direction:column;gap:7px}.ci-assy-action-row{display:flex;align-items:center;gap:5px;padding-bottom:7px;border-bottom:1px dashed #d8e2ef}.ci-assy-action-row .ci-btn:first-child{min-width:175px}.ci-group-actions{display:flex;gap:5px;flex-wrap:wrap}.ci-btn.download{border-color:#16a34a;color:#15803d}
.ci-btn.manual-cogm{background:#0f766e}.ci-price-confirm{display:flex;gap:7px;align-items:flex-start;font-size:10px;color:#475569}.ci-price-confirm[hidden]{display:none}.ci-price-confirm input{width:auto;margin-top:2px}
.ci-status-stack{display:flex;min-height:32px;max-width:285px;align-items:flex-start;flex-direction:column;gap:4px;padding:3px 0}.ci-status-stack+.ci-status-stack{border-top:1px dashed #d8e2ef}.ci-status-stack .ci-note{margin:0;padding:4px 6px;border-radius:6px;background:#fff7ed;white-space:nowrap}.ci-marketing-status{display:inline-flex;border-radius:6px;padding:4px 7px;background:#f1f5f9;color:#64748b;font-size:9px;font-weight:800;white-space:nowrap}.ci-marketing-status.die_go{background:#dcfce7;color:#15803d}.ci-marketing-status.waiting{background:#fef3c7;color:#a16207}.ci-marketing-status.cancel{background:#fee2e2;color:#b91c1c}.ci-update-box{display:inline-flex;align-items:center;gap:4px;padding:4px 6px;border:1px solid #f4c95d;border-radius:6px;background:#fffbeb;color:#92400e;font-size:9px;font-weight:800;white-space:nowrap}.ci-update-box small{display:inline;margin:0;color:#92400e;font-size:8px;font-weight:600}.ci-update-box small+small{width:100%;white-space:normal}
</style>

@if(session('success'))<div class="ci-flash">{{ session('success') }}</div>@endif
<div class="ci-card">
    <div class="ci-head">
        <div><h3>Daftar Progress Costing</h3><p>Costing tetap berstatus sedang proses sampai dikirim untuk approval.</p></div>
        <form class="ci-search" method="GET"><input name="search" value="{{ $search }}" placeholder="Cari customer, model, assy no..."><input type="hidden" name="status" value="{{ $status }}"><button class="ci-btn">Cari</button></form>
    </div>

    <div class="ci-tabs">
        @foreach(['active'=>'Aktif','history'=>'History','all'=>'Semua'] as $key=>$label)
            <a class="ci-tab {{ $status===$key?'active':'' }}" href="{{ route('costing.inbox', ['status'=>$key,'search'=>$search], false) }}">{{ $label }}</a>
        @endforeach
    </div>

    <div class="ci-wrap"><table class="ci-table"><thead><tr><th>Project</th><th>Customer</th><th>Model</th><th>No. Assy</th><th>Rev.</th><th>Progress</th><th>Status</th><th>COGM</th><th>Update</th><th>Aksi</th></tr></thead><tbody>
        @foreach($pendingCostingTasks as $task)
            @php($revision=$task->revision)
            @php($project=$task->project)
            <tr>
                <td><strong>{{ $project?->part_name ?: '-' }}</strong><small>{{ $project?->product?->name ?: '-' }}</small></td>
                <td>{{ $project?->customer ?: '-' }}</td>
                <td>{{ $project?->model ?: '-' }}</td>
                <td><strong>{{ $project?->part_number ?: '-' }}</strong></td>
                <td>{{ $revision?->version_label ?: '-' }}</td>
                <td><x-project-progress :revision="$revision" /></td>
                <td><span class="ci-status info">Menunggu Form Costing</span><small>Dokumen Breakdown telah disimpan.</small>@if($revision?->latestCostingRevision?->revision_type==='price')<div class="ci-note" style="color:#7c3aed">Update Harga · {{ $revision->latestCostingRevision->created_at?->format('d/m/Y H:i') }}</div>@endif</td>
                <td><strong>-</strong></td>
                <td>{{ optional($task->updated_at)->format('d/m/Y') }}<small>{{ optional($task->updated_at)->format('H:i') }}</small></td>
                <td><div class="ci-actions"><a class="ci-btn secondary" href="{{ url('/form') }}?tracking_revision_id={{ $revision?->id }}">Form Costing</a><button class="ci-btn revision" type="button" data-revision="{{ $revision?->id }}" data-project="{{ $project?->part_number }}" onclick="openCostingRevision(this.dataset)">Rev</button></div></td>
            </tr>
        @endforeach
        @forelse($items as $item)
            @php($revision=$item->trackingRevision)
            @php($members=$item->group_members ?? collect([$item]))
            <tr>
                <td><strong>{{ $item->assy_name ?: $revision?->project?->part_name ?: '-' }}</strong><small>{{ $item->product?->name ?: $revision?->project?->product?->name ?: '-' }}</small></td>
                <td>{{ $item->customer?->name ?: $revision?->project?->customer ?: '-' }}</td>
                <td>{{ $item->model ?: $revision?->project?->model ?: '-' }}</td>
                <td>@foreach($members as $member)@php($memberRevision=$member->trackingRevision)<div class="ci-member"><strong>{{ $member->assy_no ?: $memberRevision?->project?->part_number ?: '-' }}</strong></div>@endforeach</td>
                <td>@foreach($members as $member)@php($memberRevision=$member->trackingRevision)<div class="ci-member">{{ $memberRevision?->version_label ?: '-' }}</div>@endforeach</td>
                <td>@foreach($members as $member)@php($memberRevision=$member->trackingRevision)<div class="ci-member"><x-project-progress :revision="$memberRevision" /></div>@endforeach</td>
                <td>
                    @foreach($members as $member)
                        @php($memberRevision=$member->trackingRevision)
                        @php($submission=$memberRevision?->latestSubmission)
                        @php($latestUpdate=$memberRevision?->latestCostingRevision)
                        @php($missingCount=$memberRevision?->pricing_status==='full_price'?0:($memberRevision?->pricing_status==='incomplete'?(int)$memberRevision->manual_missing_price_count:($member->open_unpriced_count??0)))
                        <div class="ci-status-stack">
                            <span class="ci-status {{ $member->workflow_class }}">{{ $member->workflow_label }}</span>
                            <div class="ci-note">{{ $memberRevision?->pricing_status==='full_price'?'Full Price':($missingCount>0?'Belum Full Price · '.$missingCount.' part':'Harga lengkap') }}</div>
                            @if($submission?->marketing_status)<span class="ci-marketing-status {{ $submission->marketing_status }}">{{ ['waiting'=>'Waiting','cancel'=>'Cancel','die_go'=>'Die Go (Berhasil)'][$submission->marketing_status] }}</span>@endif
                            @if($latestUpdate?->revision_type==='price' && (int) $submission?->update_count > 0)<span class="ci-update-box">Update Harga {{ $submission->update_count }}x</span>@endif
                            @if($memberRevision?->status===\App\Models\DocumentRevision::STATUS_REJECTED_BY_COORDINATOR && $member->approval?->rejection_notes)<small>Catatan: {{ $member->approval->rejection_notes }}</small>@endif
                        </div>
                    @endforeach
                </td>
                <td>@foreach($members as $member)<div class="ci-member"><strong>Rp {{ number_format($member->cogm_value,0,',','.') }}</strong></div>@endforeach</td>
                <td>@foreach($members as $member)<div class="ci-member update"><span>{{ optional($member->updated_at)->format('d/m/Y') }}</span><small>{{ optional($member->updated_at)->format('H:i') }}</small></div>@endforeach</td>
                <td><div class="ci-actions grouped">
                    @foreach($members as $member)@php($memberRevision=$member->trackingRevision)<div class="ci-assy-action-row"><a class="ci-btn secondary" href="{{ url('/form') }}?tracking_revision_id={{ $memberRevision?->id }}{{ $memberRevision?->status === \App\Models\DocumentRevision::STATUS_SUBMITTED_TO_MARKETING ? '&edit_submitted=1' : '' }}">Form {{ $member->assy_no ?: $memberRevision?->project?->part_number }}</a>@if($memberRevision?->cogm_export_file_path || $memberRevision?->cogm_import_file_path)<a class="ci-btn secondary download" href="{{ route('costing.cogm.download',$memberRevision,absolute:false) }}" title="{{ $memberRevision->cogm_import_original_name ?: $memberRevision->cogm_export_original_name }}">Download COGM</a>@endif<button class="ci-btn manual-cogm" type="button" data-revision="{{ $memberRevision?->id }}" data-project="{{ $member->assy_no ?: $memberRevision?->project?->part_number }}" onclick="openManualCogm(this.dataset)">Upload Update COGM</button></div>@endforeach
                    <div class="ci-group-actions">
                    <button class="ci-btn revision" type="button" data-revision="{{ $revision?->id }}" data-project="{{ $item->assy_no ?: $revision?->project?->part_number }}" onclick="openCostingRevision(this.dataset)">Rev</button>
                    @if($item->can_submit_approval)<form method="POST" action="{{ route('costing-approvals.submit',$revision,absolute:false) }}" class="js-confirm-form" data-confirm-title="Submit Costing" data-confirm-message="Costing {{ $item->assy_no }} akan dikirim ke Coordinator Costing untuk diperiksa dan dikunci sementara selama proses approval." data-confirm-button="Ya, Submit Costing" data-confirm-tone="primary">@csrf<button class="ci-btn">Submit Approval</button></form>@endif
                    @if($item->can_approve)<form method="POST" action="{{ route('costing-approvals.approve',$revision,absolute:false) }}" class="js-confirm-form" data-confirm-title="Approve COGM" data-confirm-message="COGM {{ $item->assy_no }} akan disetujui dan dapat dilanjutkan untuk dikirim ke Team Marketing." data-confirm-button="Ya, Approve COGM" data-confirm-tone="primary">@csrf<button class="ci-btn success">Approve</button></form>@endif
                    @if($item->can_send)<form method="POST" action="{{ route('costing-approvals.send-marketing',$revision,absolute:false) }}" class="js-confirm-form" data-confirm-title="Kirim COGM" data-confirm-message="COGM {{ $item->assy_no }} akan dikirim ke Team Marketing dan progress project akan ditandai selesai." data-confirm-button="Ya, Kirim Marketing" data-confirm-tone="primary">@csrf<input type="hidden" name="pic_marketing" value="{{ $revision?->pic_marketing }}"><button class="ci-btn success">Kirim Marketing</button></form>@endif
                    </div>
                </div></td>
            </tr>
        @empty
            @if($pendingCostingTasks->isEmpty())<tr><td colspan="10" class="ci-empty">Tidak ada progress costing pada filter ini.</td></tr>@endif
        @endforelse
    </tbody></table></div>
    <div class="ci-pagination">{{ $items->links() }}</div>
</div>
<dialog class="ci-revision-modal" id="costingRevisionModal"><form id="costingRevisionForm" method="POST" enctype="multipart/form-data">@csrf<div class="ci-revision-head"><div><strong>Upload Revisi Costing</strong><small id="costingRevisionProject" style="display:block;color:#ddd6fe">Project</small></div><button type="button" onclick="costingRevisionModal.close()">&times;</button></div><div class="ci-revision-body"><div class="ci-revision-field"><label>Jenis Update *</label><select name="revision_type" required><option value="">Pilih jenis update</option><option value="partlist">Update Partlist</option><option value="umh">Update UMH</option></select></div><div class="ci-revision-field"><label>File Excel *</label><input type="file" name="revision_file" accept=".xls,.xlsx" required></div><div class="ci-revision-field"><label>Keterangan</label><textarea name="description" placeholder="Jelaskan perubahan yang dilakukan..."></textarea></div></div><div class="ci-revision-foot"><button class="ci-btn secondary" type="button" onclick="costingRevisionModal.close()">Batal</button><button class="ci-btn" type="submit">Upload Revisi</button></div></form></dialog>
<dialog class="ci-revision-modal" id="manualCogmModal"><form id="manualCogmForm" method="POST" enctype="multipart/form-data">@csrf<div class="ci-revision-head"><div><strong>Upload Update COGM</strong><small id="manualCogmProject" style="display:block;color:#ccfbf1">Project</small></div><button type="button" onclick="manualCogmModal.close()">&times;</button></div><div class="ci-revision-body"><div class="ci-revision-field"><label>File COGM Excel *</label><input type="file" name="cogm_file" accept=".xls,.xlsx" required></div><div class="ci-revision-field"><label>Nomor Update Harga *</label><input type="number" name="price_update_number" min="1" max="999" placeholder="Contoh: 1" required></div><div class="ci-revision-field"><label>Status Harga *</label><select name="pricing_status" id="manualCogmPricingStatus" required onchange="toggleManualCogmStatus()"><option value="incomplete">Belum Full Price</option><option value="full_price">Full Price · Harga lengkap</option></select></div><div class="ci-revision-field" id="manualCogmMissingWrap"><label>Jumlah part belum memiliki harga *</label><input type="number" name="missing_price_count" min="1" value="1"></div><label class="ci-price-confirm" id="manualCogmConfirmWrap" hidden><input type="checkbox" name="full_price_confirmation" value="1"><span>Saya memastikan seluruh harga dalam file sudah lengkap dan final.</span></label><div class="ci-revision-field"><label>Keterangan</label><textarea name="description" placeholder="Jelaskan perubahan dalam file COGM..."></textarea></div></div><div class="ci-revision-foot"><button class="ci-btn secondary" type="button" onclick="manualCogmModal.close()">Batal</button><button class="ci-btn manual-cogm" type="submit">Gunakan File Ini</button></div></form></dialog>
<script>const costingRevisionModal=document.getElementById('costingRevisionModal'),costingRevisionForm=document.getElementById('costingRevisionForm'),manualCogmModal=document.getElementById('manualCogmModal'),manualCogmForm=document.getElementById('manualCogmForm');function openCostingRevision(data){costingRevisionForm.reset();costingRevisionForm.action=@json(url('/costing/revisions'))+'/'+data.revision;document.getElementById('costingRevisionProject').textContent=data.project||'Project';costingRevisionModal.showModal()}function openManualCogm(data){manualCogmForm.reset();manualCogmForm.action=@json(url('/costing/revisions'))+'/'+data.revision+'/manual-cogm';document.getElementById('manualCogmProject').textContent=data.project||'Project';toggleManualCogmStatus();manualCogmModal.showModal()}function toggleManualCogmStatus(){const full=document.getElementById('manualCogmPricingStatus').value==='full_price',missing=document.querySelector('#manualCogmMissingWrap input'),confirmation=document.querySelector('#manualCogmConfirmWrap input');document.getElementById('manualCogmMissingWrap').hidden=full;document.getElementById('manualCogmConfirmWrap').hidden=!full;missing.required=!full;confirmation.required=full}</script>
@endsection
